jenkins-infra/helm-charts

- charts/accountapp/Chart.yaml
- charts/accountapp/values.yaml
Follows up #15 and #16 but for accountapp.
> feat(accountapp) default image tag is 'latest'

- charts/chatbot/Chart.yaml
- charts/chatbot/README.md
- charts/chatbot/values.yaml
Signed-off-by: Damien Duportal <damien.duportal@gmail.com>
> feat(chatbot) use tag 'latest' as default

- charts/jenkins-additional/Chart.yaml
- charts/jenkins-additional/README.md
- charts/jenkins-additional/templates/cluster-admin.yaml
- charts/jenkins-additional/templates/jenkins-secrets.yaml
- charts/jenkins-additional/values.yaml
Ref: https://github.com/jenkins-infra/charts/pull/1685#issuecomment-965073437
> feat: chart for additional jenkins templates

- charts/incrementals-publisher/Chart.yaml
- charts/incrementals-publisher/values.yaml
Signed-off-by: Damien Duportal <damien.duportal@gmail.com>
> feat(incrementals-publisher) use tag 'latest' as default

- charts/plugin-site-issues/.helmignore
- charts/plugin-site-issues/Chart.yaml
- charts/plugin-site-issues/README.md
- charts/plugin-site-issues/templates/NOTES.txt
- charts/plugin-site-issues/templates/_helpers.tpl
- charts/plugin-site-issues/templates/deployment.yaml
- charts/plugin-site-issues/templates/hpa.yaml
- charts/plugin-site-issues/templates/ingress.yaml
- charts/plugin-site-issues/templates/secret.yaml
- charts/plugin-site-issues/templates/service.yaml
- charts/plugin-site-issues/templates/serviceaccount.yaml
- charts/plugin-site-issues/templates/tests/test-connection.yaml
- charts/plugin-site-issues/values.yaml
https://github.com/jenkins-infra/public-charts/pull/31
https://github.com/jenkins-infra/charts-secrets/pull/20
https://github.com/jenkins-infra/charts/pull/1790
> Plugin site issues helm chart

- charts/plugin-site-issues/Chart.yaml
- charts/plugin-site-issues/templates/deployment.yaml
Was supposed to be github app private key, not jira
> [plugin-site-issues] Rename env variable

- charts/plugin-site/Chart.yaml
- charts/plugin-site/values.yaml
I think this is old enough not to have updatecli hooked up?
> Update plugin-site-api to 266-ab61e2

- updatecli/updatecli.d/custom-distribution-service.yaml
- updatecli/updatecli.d/incrementals-publisher.yaml
- updatecli/updatecli.d/jenkins-wiki-exporter.yaml
- updatecli/updatecli.d/ldap.yaml
- updatecli/updatecli.d/mirrorbits.yaml
- updatecli/updatecli.d/uplink.yaml
- updatecli/updatecli.d/wiki.yaml
> fix: add missing scm block to the updateChartVersion targets

- charts/incrementals-publisher/Chart.yaml
- charts/incrementals-publisher/templates/deployment.yaml
- charts/incrementals-publisher/templates/secret.yaml
See https://github.com/jenkins-infra/incrementals-publisher/pull/21
> Add github app support to incrementals

- updatecli/updatecli.d/nginx.yaml
Signed-off-by: Damien Duportal <damien.duportal@gmail.com>
> chore(updatecli) ensure that only nginx stable version is tracked

- updatecli/updatecli.d/rating.yaml
to keep the rating image uptodate with updatecli
> chore (updatecli/rating): updatecli manifest for rating

- charts/plugin-site-issues/Chart.yaml
- charts/plugin-site-issues/templates/deployment.yaml
Ref: https://github.com/jenkins-infra/helpdesk/issues/2882#issuecomment-1097922748
> fix(plugin-site-issues) correct healthcheck path

- charts/jenkins-jobs/Chart.yaml
> hotfix bump jenkins-jobs version

- charts/httpredirector/Chart.yaml
- charts/httpredirector/templates/ingress.yaml
- charts/httpredirector/tests/defaults_test.yaml
- charts/httpredirector/tests/withvalues_test.yaml
- charts/httpredirector/values.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/2943
> chore(httpredirector): template the ingressClassName value

- charts/ldap/Chart.yaml
- charts/ldap/templates/persistentVolume.yaml
Ref. https://github.com/Azure/AKS/issues/2871
Signed-off-by: Damien Duportal <damien.duportal@gmail.com>
> hotfix(ldap) specify secretNamespace for ldap-backup PV

- charts/nginx-proxy/Chart.yaml
- charts/nginx-proxy/templates/ingress.yaml
- charts/nginx-proxy/templates/secret.yaml
Ref: https://github.com/jenkins-infra/helpdesk/issues/2752
> feat(nginx-proxy): add basic auth

- charts/nginx-proxy/Chart.yaml
- charts/nginx-proxy/templates/ingress.yaml
- charts/nginx-proxy/templates/secret.yaml
- charts/nginx-proxy/values.yaml
Ref: error from https://github.com/jenkins-infra/kubernetes-management/pull/2750
> fix(nginx-proxy): set default values for auth

- charts/plugin-health-scoring/Chart.yaml
- charts/plugin-health-scoring/templates/deployment.yaml
Fixup of https://github.com/jenkins-infra/helm-charts/pull/219
> fixup: remove checksum on empty removed secret

- charts/plugin-health-scoring/Chart.yaml
- charts/plugin-health-scoring/templates/deployment.yaml
- charts/plugin-health-scoring/values.yaml
Fixup of https://github.com/jenkins-infra/helm-charts/pull/219
> fixup(plugin-health-scoring): align database.username too

- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/templates/nginx-proxy-configmap.yaml
- charts/artifact-caching-proxy/templates/statefulset.yaml
- charts/artifact-caching-proxy/values.yaml
Trying to debug more easily my issue with the /var/cache/nginx/lost+root owner as root.
> fix(artifact-caching-proxy): better initContainers command

- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/templates/nginx-proxy-configmap.yaml
- charts/artifact-caching-proxy/templates/service.yaml
- charts/artifact-caching-proxy/templates/statefulset.yaml
- charts/artifact-caching-proxy/values.yaml
Ref: https://github.com/jenkins-infra/helpdesk/issues/2752 & https://docs.datadoghq.com/integrations/nginx/
> feat(artifact-caching-proxy): Datadog metrics and log collection

- updatecli/updatecli.d/rss2twitter.yaml
Ref: https://github.com/jenkins-infra/helpdesk/issues/3085
> chore(rss2twitter): add updatecli manifest

- CODEOWNERS
Replace https://github.com/jenkins-infra/helm-charts/pull/243
> chore: add CODEOWNERS, with alecharp as owner of the Plugin Health Scoring chart

- charts/plugin-health-scoring/Chart.yaml
- charts/plugin-health-scoring/tests/custom_values_test.yaml
- charts/plugin-health-scoring/tests/defaults_test.yaml
> fix(plugin-health-scoring): correct decoded base64 value in comment

- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/templates/nginx-default-configmap.yaml
- charts/artifact-caching-proxy/templates/nginx-proxy-configmap.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/2322
Depends on https://github.com/jenkins-infra/helm-charts/pull/399
Documentation pointed in comments to help understanding the scope of this change:
- https://docs.nginx.com/nginx/admin-guide/web-server/serving-static-content/#enabling-sendfile
- https://www.sobyte.net/post/2022-08/nginx-send/
=> This change will have to be validated, once deployed, using metrics!
> feat(acp) Improve I/O perfomances

- charts/jenkinsio/Chart.yaml
- charts/jenkinsio/templates/nginx-configmap.yaml
In case anyone relies on the old domain.
> Update nginx GPG key rewrite

- charts/mirrorbits/Chart.yaml
- charts/mirrorbits/README.md
Ref: https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1591316525
> cleanup: remove `mirror.azure.jenkins.io` from `mirrorbits` helm chart README

- charts/mirrorbits/Chart.yaml
- charts/mirrorbits/templates/service.files.yaml
- charts/mirrorbits/tests/custom_values_test.yaml
- charts/mirrorbits/tests/defaults_test.yaml
- charts/mirrorbits/values.yaml
> fix(mirrorbits): correct service selector label

- .github/workflows/check-chart-versions-bump.yml
This PR adds a GitHub Action which can be used as a check on pull request to ensure any modified chart has their version bumped (compared to the PR target branch version)
Tested on a personal repository.
> feat: add a required check on chart version bump

- .github/workflows/check-chart-versions-bump.yml
There was some errors in the initial version 🙈 
This one also allow checking all modified charts instead of stopping at the first unbumped version.
> fixup: check-chart-versions-bump.yml

- .github/workflows/test.yml
> fix(helm-unittest): correct step name for `setup helm` step input

- charts/mirrorbits-parent/.gitignore
- charts/mirrorbits-parent/Chart.yaml
> chore(mirrorbits-parent): ignore `charts` folder

- charts/rsyncd/Chart.yaml
- charts/rsyncd/templates/deployment.yaml
- charts/rsyncd/tests/custom_values_test.yaml
- charts/rsyncd/tests/defaults_test.yaml
> feat(rsyncd) use tmpfs for `/tmp` and `/rsync/run` directories

- updatecli/updatecli.d/httpd.yaml
Noticed in https://github.com/jenkins-infra/helm-charts/pull/671
> chore(httpd): set updatecli `target.versionincrement` to `patch`

- updatecli/updatecli.d/accountapp.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3619 following https://github.com/jenkins-infra/account-app/pull/299
⚠️ WARNING ⚠️ updatecli doesn't take care of this for now : https://github.com/updatecli/updatecli/issues/1582
> chore(updatecli): add an arm64 architecture condition to accountapp

- charts/wiki/Chart.yaml
- charts/wiki/values.yaml
minAvailable or maxUnavailable
> fix(wiki): PDB only one option possible not both 

- charts/wiki/Chart.yaml
- charts/wiki/templates/pdb.yaml
- charts/wiki/tests/custom_values_test.yaml
correct https://github.com/jenkins-infra/helm-charts/pull/707
as per https://github.com/jenkins-infra/helpdesk/issues/3719
> fix(PDB): correct the selector for wiki PDB

- charts/mirrorbits-lite/Chart.yaml
- charts/mirrorbits-lite/templates/deployment.yaml
- charts/mirrorbits-lite/tests/custom_values_test.yaml
- charts/mirrorbits-lite/tests/defaults_test.yaml
- charts/mirrorbits-lite/tests/secrets_default_values.yaml
- charts/mirrorbits-lite/values.yaml
Cherry pick of #730 and #732 to `mirrorbits-lite`
Includes an update of the chart metadatas
> feat(mirrorbits-lite) use a volume for logs

- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/templates/statefulset.yaml
- charts/artifact-caching-proxy/tests/affinity_test.yaml
- charts/artifact-caching-proxy/tests/defaults_test.yaml
as per https://github.com/jenkins-infra/kubernetes-management/pull/4429#pullrequestreview-1643670963
> feat(acp): adding affinity with unittest

- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/templates/pdb.yaml
- charts/artifact-caching-proxy/tests/custom_values_test.yaml
- charts/artifact-caching-proxy/tests/defaults_test.yaml
> feat(artifact-caching-proxy): add PodDisruptionBudget

- charts/jenkinsio/Chart.yaml
- charts/jenkinsio/templates/deployment.yaml
- charts/jenkinsio/templates/zh-deployment.yaml
- charts/jenkinsio/tests/custom_values_test.yaml
- charts/jenkinsio/tests/defaults_values_test.yaml
- charts/jenkinsio/values.yaml
BREAKING CHANGE.
Related to https://github.com/jenkins-infra/kubernetes-management/pull/4430
> feat!(jenkinsio) 💥 allow specifying custom affinities per deployment.

- charts/javadoc/Chart.yaml
- charts/javadoc/templates/_helpers.tpl
- charts/javadoc/templates/deployment.yaml
- charts/javadoc/templates/pdb.yaml
- charts/javadoc/tests/custom_values_test.yaml
- charts/javadoc/tests/defaults_test.yaml
- charts/javadoc/values.yaml
> feat(javadoc): adding PodDisruptionBudget to javadoc

- charts/mirrorbits/Chart.yaml
- charts/mirrorbits/templates/_helpers.tpl
- charts/mirrorbits/templates/deployment.files.yaml
- charts/mirrorbits/templates/deployment.rsyncd.yaml
- charts/mirrorbits/templates/deployment.yaml
- charts/mirrorbits/tests/custom_values_test.yaml
- charts/mirrorbits/tests/defaults_test.yaml
- charts/mirrorbits/values.yaml
need to update https://github.com/jenkins-infra/kubernetes-management/pull/4431/
> feat!(mirrorbits) 💥 allow specifying custom affinities per deployment

- charts/jenkinsio/Chart.yaml
- charts/jenkinsio/templates/_helpers.tpl
- charts/jenkinsio/templates/pdb-zh.yaml
- charts/jenkinsio/templates/pdb.yaml
- charts/jenkinsio/tests/custom_values_test.yaml
- charts/jenkinsio/tests/defaults_values_test.yaml
- charts/jenkinsio/values.yaml
> feat(jenkinsio): add PodDisruptionBudget to jenkinsio and jenkinsio-zh with there unittest

- charts/plugin-health-scoring/Chart.yaml
- charts/plugin-health-scoring/values.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3619#issuecomment-1713522131
> bump(PHS): bump to 2.8.0 with arm64 compatible image

- charts/mirrorbits-lite/Chart.yaml
- charts/mirrorbits-lite/templates/_helpers.tpl
- charts/mirrorbits-lite/templates/pdb.yaml
- charts/mirrorbits-lite/tests/custom_values_test.yaml
- charts/mirrorbits-lite/tests/defaults_test.yaml
- charts/mirrorbits-lite/values.yaml
This PR cherry picks the work from @smerle33 in https://github.com/jenkins-infra/helm-charts/pull/828 (for https://github.com/jenkins-infra/helpdesk/issues/3719)
> feat(mirrorbits-lite) create a PDB when application is replicated

- charts/plugin-site/Chart.yaml
- charts/plugin-site/values.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3778
This PR embeds a few changes so we will have to watch carefully when deployed to production!
> feat(plugin-site) bump backend image tag to `294-5389ef`

- charts/ldap/Chart.yaml
- charts/ldap/tests/custom_values_test.yaml
- charts/ldap/tests/defaults_values_test.yaml
- charts/ldap/values.yaml
> fix(ldap): fix helm templating and add unit tests

- charts/mirrorbits-parent/Chart.yaml
- charts/mirrorbits-parent/templates/serviceaccount.yaml
- charts/mirrorbits-parent/tests/custom_values_serviceaccount_test.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/2649
Required by https://github.com/jenkins-infra/update-center2/blob/be3e96b613d1fe6743cf569d21577e425baf312c/site/publish.sh#L108
> fix(mirrorbits-parents) ensure mirrorbits svcaccount can list pods

- charts/nginx-website/Chart.yaml
- charts/nginx-website/templates/deployment.yaml
- charts/nginx-website/templates/secret.yaml
- charts/nginx-website/values.yaml
Fixup of #959 
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3809#issuecomment-1822357561
> fix(nginx-website): don't hardcode configmap and secret name

- .github/workflows/test.yml
Same player starts again... Follow-up of #1020
Tested by executing the script in local on #1014, #1017 and #1019
> fix(GHA/test): don't try to retrieve modified files from PR if not in a PR

- charts/jenkinsio/Chart.yaml
- charts/jenkinsio/README.md
updates the outdated instructions on https://github.com/jenkins-infra/helm-charts/tree/main/charts/jenkinsio#running-this-yourself
https://github.com/jenkins-infra/helm-charts/issues/944
> docs(jenkinsio) update instructions 

- charts/ldap/Chart.yaml
- charts/ldap/values.yaml
- updatecli/updatecli.d/ldap.yaml
ref. https://github.com/jenkins-infra/helpdesk/issues/3837#issuecomment-1898378430
This PR also includes updatecli manifest
> feat(ldap) pin image version to the tag `1.0.1`

- charts/jenkinsio/Chart.yaml
- charts/jenkinsio/README.md
Update values.local.yaml in readme to reference serviceName.
https://github.com/jenkins-infra/kubernetes-management/blob/main/config/jenkinsio.yaml#L12-L15
https://github.com/jenkins-infra/helm-charts/issues/1069
> Jenkinsio chart update Readme

- charts/jenkins-kubernetes-agents/Chart.yaml
- charts/jenkins-kubernetes-agents/templates/serviceaccount.yaml
Disable service account token automount for chart: jenkins-kubernetes-agent 
https://github.com/jenkins-infra/helm-charts/issues/261
> chart: jenkins-kubernetes-agent "disable token automount"

- charts/httpd/Chart.yaml
- charts/httpd/templates/configmap.yaml
- charts/httpd/tests/custom_values_test.yaml
- charts/httpd/values.yaml
This PR allows to set a custom httpd conf.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2068909070
> feat(httpd): allow to set a custom httpd conf

- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/templates/nginx-proxy-configmap.yaml
- charts/artifact-caching-proxy/tests/proxy_cache_config_test.yaml
- charts/artifact-caching-proxy/values.yaml
This PR adds an optional authirization header to the values.yaml
Fixes #1156
> Add optional authorization header

- charts/httpd/Chart.yaml
- charts/httpd/templates/httpdRestart.yaml
> hotfix(httpd): container for cronjob need lowercase only

- charts/nginx-website/Chart.yaml
- charts/nginx-website/templates/nginx-configmap.yaml
- charts/nginx-website/tests/custom_values_locations_test.yaml
- charts/nginx-website/tests/values/custom.yaml
- charts/nginx-website/values.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4132#issuecomment-2352333521
allow to provide a overrideLocations key to custom the locations within the nginx configuration file.
> feat(nginx-website): add overrideLocations option

- charts/mirrorbits/Chart.yaml
- charts/mirrorbits/templates/deployment.yaml
- charts/mirrorbits/tests/custom_values_test.yaml
- charts/mirrorbits/tests/values/custom.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4402
Fixup of #1449
> fix(mirrorbits) correct volume mount subpath for repository

- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/templates/nginx-proxy-configmap.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4442#issuecomment-2624740803
> fix(acp) tune proxy timeouts

- charts/geoipupdates/Chart.yaml
- charts/geoipupdates/templates/cronjob.yaml
- charts/geoipupdates/tests/custom_values_test.yaml
- charts/geoipupdates/tests/defaults_test.yaml
- charts/geoipupdates/tests/values/custom_geoipupdater.yaml
- charts/geoipupdates/values.yaml
> feat(geoipupdates) allow specifying custom pod annotations

- charts/uplink/Chart.yaml
- charts/uplink/templates/deployment.yaml
- charts/uplink/tests/custom_values_test.yaml
- charts/uplink/tests/defaults_test.yaml
- charts/uplink/tests/values/custom.yaml
- charts/uplink/values.yaml
> feat(uplink) allow custom pod annotations

- charts/plugin-site/Chart.yaml
- charts/plugin-site/templates/deployment-backend.yaml
- charts/plugin-site/templates/deployment-frontend.yaml
- charts/plugin-site/tests/custom_values_test.yaml
- charts/plugin-site/tests/defaults_values_test.yaml
- charts/plugin-site/tests/values/custom.yaml
- charts/plugin-site/values.yaml
> feat(plugin-site) allow custom pod annotations

- charts/accountapp/Chart.yaml
- charts/accountapp/templates/_helpers.tpl
> fix(accountapp) update chart maintainers and remove them from the PDB labels

- charts/jenkinsio/Chart.yaml
- charts/jenkinsio/templates/_helpers.tpl
- charts/jenkinsio/templates/deployment.yaml
- charts/jenkinsio/templates/zh-deployment.yaml
- charts/jenkinsio/tests/custom_values_test.yaml
- charts/jenkinsio/tests/defaults_values_test.yaml
- charts/jenkinsio/tests/values/custom.yaml
- charts/jenkinsio/values.yaml
> feat(jenkinsio) allow custom pod annotations

- charts/accountapp/Chart.yaml
- charts/accountapp/templates/deployment.yaml
- charts/accountapp/tests/custom_values_test.yaml
- charts/accountapp/tests/defaults_test.yaml
- charts/accountapp/tests/values/custom.yaml
- charts/accountapp/values.yaml
- updatecli/updatecli.d/accountapp.yaml
> feat(accountapp) allow custom pod annotations

- charts/incrementals-publisher/Chart.yaml
- charts/incrementals-publisher/templates/deployment.yaml
- charts/incrementals-publisher/tests/custom_values_test.yaml
- charts/incrementals-publisher/tests/defaults_test.yaml
- charts/incrementals-publisher/tests/values/custom.yaml
- charts/incrementals-publisher/values.yaml
> feat(incrementals-publisher) allow custom pod annotations

- charts/mirrorbits/Chart.yaml
- charts/mirrorbits/templates/_helpers.tpl
- charts/mirrorbits/tests/custom_values_test.yaml
- charts/mirrorbits/tests/values/custom.yaml
- charts/mirrorbits/values.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4691
> feat(mirrorbits) implement Redis Sentinel configuration support

- charts/nginx-website/Chart.yaml
- charts/nginx-website/templates/deployment.yaml
- charts/nginx-website/tests/custom_values_test.yaml
- charts/nginx-website/tests/defaults_test.yaml
- charts/nginx-website/tests/values/custom.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4767
> feat(nginx-website) allow subPath html volume mount and enforce readOnly
