- charts/accountapp/templates/ingress.yaml
- charts/accountapp/values.yaml
- charts/custom-distribution-service/templates/ingress.yaml
- charts/custom-distribution-service/values.yaml
- charts/incrementals-publisher/templates/ingress.yaml
- charts/incrementals-publisher/values.yaml
- charts/javadoc/templates/ingress.yaml
- charts/javadoc/values.yaml
- charts/jenkins-wiki-exporter/templates/ingress.yaml
- charts/jenkins-wiki-exporter/values.yaml
- charts/jenkinsio/templates/ingress.yaml
- charts/jenkinsio/values.yaml
- charts/keycloak/templates/ingress.yaml
- charts/keycloak/values.yaml
- charts/mirrorbits/templates/ingress.yaml
- charts/mirrorbits/values.yaml
- charts/plugin-site/templates/ingress.yaml
- charts/plugin-site/values.yaml
- charts/reports/templates/ingress.yaml
- charts/reports/values.yaml
- charts/uplink/templates/ingress.yaml
- charts/uplink/values.yaml
- replace "ingressClassName" field in values.yaml by "className" (no need for "ingress" prefix), and set its default empty value
- set $svcPort value at the beginnning of the ingress templates so we won't need to cast it to `int` in the range ports of ingressses
Ref: https://issues.jenkins.io/projects/INFRA/issues/INFRA-3109
> fix: improve charts [INFRA-3109]

- charts/mirrorbits/Chart.yaml
- charts/mirrorbits/templates/ingress.yaml
- charts/mirrorbits/templates/service.yaml
- charts/mirrorbits/values.yaml
fix 'templates/: template: mirrorbits/templates/NOTES.txt:8:39: executing mirrorbits/templates/NOTES.txt at <.Values.service.type>: wrong type for value; expected string; got interface {}'
Ref: https://github.com/jenkins-infra/charts/pull/1642#pullrequestreview-799185857
> fix(mirrorbits): put mirrorbits service values on root service

- charts/jenkinsio/Chart.yaml
- charts/jenkinsio/templates/nginx-configmap.yaml
Was here before: https://github.com/jenkins-infra/charts/blob/main/config/jenkinsio.yaml\#L7-L13
Moved in the chart in order to get rid of nginx.ingress.kubernetes.io/configuration-snippet triggering error related to https://github.com/kubernetes/ingress-nginx/issues/7837
> fix(jenkinsio): nginx config moved from helmfile configuration

- charts/plugin-site/Chart.yaml
- charts/plugin-site/templates/nginx-configmap.yaml
Nginx will load both files successfully, and canonical meta tag will
merge any seo type things.
This allows for /:pluginname/issues to work
> No longer rewrite /foo to /foo/

- index.html
The [current gh-pages index](https://jenkins-infra.github.io/helm-charts) doesn't provide such useful information:
With this PR, consulting https://jenkins-infra.github.io/helm-charts with a browser (for the devs) will redirect to this Github repository homepage, which can be handy when wanting to know more about a chart than just the command to add the helm repo.
It doesn't touch the index.yaml, nothing change on the helm side.
> feat(gh-pages): add an index.html to redirect the Helm charts repository URL to the Github repository

- updatecli/updatecli.d/mirrorbits.yaml
This PR ensures that updatecli tracks geoip image version for mirrorbits.
It also fixes the manifest to be compliant with updatecli 0.18.0.
> chore(updatecli) track geoip image version for mirrorbits

- updatecli/updatecli.d/nginx.yaml
Fixes jenkins-infra/kubernetes-management#1895, jenkins-infra/kubernetes-management#1936
> fix: bump modified helm chart version in nginx manifest

- charts/jenkins-jobs/Chart.yaml
- charts/jenkins-jobs/README.md
- charts/jenkins-jobs/templates/_helpers.tpl
- charts/jenkins-jobs/templates/jcasc-jobs-config.yaml
- charts/jenkins-jobs/values.yaml
This PR adds a new helm charts which goal is to generate a configmap with the "JCasc+job-dsl" configuration generated from a YAML structure from the helm values.
It's aimed at solving https://github.com/jenkins-infra/helpdesk/issues/2840.
This first version of the chart is targeted at replacing the actual [infra.ci job-dsl "raw" config](https://github.com/jenkins-infra/kubernetes-management/blob/main/config/ext_jenkins-infra.yaml#L518-L723) and supports the following:
- Jobs of types "folder" and "multibranch"
- Credentials per jobs, of types "string", "file", "usernamePassword", "sshUsernameKey", "azure-serviceprincipal" and "aws-credential"
- A bunch of "opinionated job-dsl defaults" related to the current [infra.ci job-dsl "raw" …
> feat(jenkins-jobs) add a new custom chart to allow generating the job-dsl config map

- Jenkinsfile_k8s
The Jenkins builds of this repository are failing with the error message `ERROR: Could not find credentials entry with ID 'updatecli-github-token'`.
It happens since https://github.com/jenkins-infra/kubernetes-management/pull/2138 because the credential `updatecli-github-token` was removed.
It is expected that we use the GitHub app credential instead (thanks @to @lemeurherve 's awesome work).
This PR intent is to fix this behavior by using the default credential of the `updatecli()` pipeline library (which is the github app credential).
> chore(jenkinsfile) delegate credential to updatecli library + ensure it runs daily

- charts/jenkins-jobs/Chart.yaml
- charts/jenkins-jobs/templates/_helpers.tpl
> fix: use correct separator between blacklist labels

- charts/jenkins-jobs/templates/_helpers.tpl
This PR fixes #110 by defaulting the multibranch to the id property (if `.fullId` is undefined) + cleaning up empty line
> fix(jenkins-jobs) fix empty ID for top-level multibranch jobs

- charts/jenkins-jobs/Chart.yaml
- charts/jenkins-jobs/templates/_helpers.tpl
This PR closes #104, and also fix a bug introduced in #111 around folder jobs.
> fix(jenkins-jobs) correct SSH credentials + folder jobs syntax

- charts/jenkins-jobs/Chart.yaml
- charts/jenkins-jobs/templates/_helpers.tpl
This PR fixes #109 by adding support for githubapp credentials.
Please not that it supports 3 different possible cases for the attribute `appid`, given the risk of mistyping by end users 😅
> feat(jenkins-jobs) add support of githubapp credentials

- updatecli/updatecli.d/custom-distribution-service.yaml
- updatecli/updatecli.d/incrementals-publisher.yaml
- updatecli/updatecli.d/jenkins-wiki-exporter.yaml
- updatecli/updatecli.d/ldap.yaml
- updatecli/updatecli.d/mirrorbits.yaml
- updatecli/updatecli.d/nginx.yaml
- updatecli/updatecli.d/plugin-site-issues.yaml
- updatecli/updatecli.d/rating.yaml
- updatecli/updatecli.d/uplink.yaml
- updatecli/updatecli.d/wiki.yaml
This PR updates updatecli manifests + ensure that the Docker image tag for plugin-site-issue is automatically tracked (with check).
> chore(updatecli) fix manifest issues for 0.23.x + track plugin-site-issues docker image

- charts/jenkins-jobs/Chart.yaml
- charts/jenkins-jobs/templates/_helpers.tpl
- charts/jenkins-jobs/values.yaml
This PR follows up https://github.com/jenkins-infra/helpdesk/issues/2884 and introduce the following changes:
- GitHub Checks are disabled by default (only pipeline status is reported)
- You can enable them by specifying the new attribute `enableGitHubChecks: true`
- The former attribute `disableGitHubChecks` is deprecated (and ignored)
- GitHub Checks default name is back to `jenkins`
- You can customize it by specifying the new name with the new `githubCheckName` attribute
> feat(jenkins-jobs) change github checks defaults + allow customization

- charts/httpredirector/Chart.yaml
- charts/httpredirector/templates/ingress.yaml
- charts/httpredirector/tests/defaults_test.yaml
- charts/httpredirector/tests/withvalues_test.yaml
- charts/httpredirector/values.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/2943
This PR enables TLS (with the certmanager annotation for our environment) by default.
> feat(httpredirector) enable tls by default with certmanager annotation

- charts/env-jenkins-release/Chart.yaml
- charts/env-jenkins-release/templates/core-packages.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/3037 and https://github.com/Azure/AKS/issues/2871
as per the AKS CSI for Kube 1.22+ (ref. https://github.com/jenkins-infra/helpdesk/issues/2930), we have to specify the namespace where the SAS token lives, otherwises Kubernetes searches on the `default` namespace.
- Same hotfix as https://github.com/jenkins-infra/helm-charts/pull/158 but for the release.ci.jenkins.io environment
- Long term fix: as https://github.com/jenkins-infra/helpdesk/issues/2930 will underline, we need to check all of the PVs to use the latest CSI driver, or at least patch all the remaining `azurefile` PVs.
> hotfix(env-jenkins-release) specify the secret namespace

- charts/plugin-health-scoring/Chart.yaml
- charts/plugin-health-scoring/templates/deployment.yaml
- charts/plugin-health-scoring/templates/secret.yaml
- charts/plugin-health-scoring/values.yaml
Allowing us to terraform output similar secrets:
- https://github.com/jenkins-infra/azure/blob/b7fe7ac9e238ee1172f0bdac7188f720ba99dd8c/rating.jenkins.io.tf#L23-L27
- https://github.com/jenkins-infra/azure/blob/b7fe7ac9e238ee1172f0bdac7188f720ba99dd8c/plugin-health.jenkins.io.tf#L23-L27
Also, removed secret.yaml (unused), and Charts.yaml/appVersion (we're using and updating values.yaml/image.tag)
> chore: align database parameter names with existing ones

- charts/accountapp/Chart.yaml
- charts/accountapp/values.yaml
- updatecli/updatecli.d/accountapp.yaml
- updatecli/updatecli.d/custom-distribution-service.yaml
- updatecli/updatecli.d/incrementals-publisher.yaml
- updatecli/updatecli.d/ldap.yaml
- updatecli/updatecli.d/mirrorbits.yaml
- updatecli/updatecli.d/nginx.yaml
- updatecli/updatecli.d/plugin-health-scoring.yaml
- updatecli/updatecli.d/plugin-site-issues.yaml
- updatecli/updatecli.d/rating.yaml
- updatecli/updatecli.d/uplink.yaml
- updatecli/updatecli.d/wiki.yaml
Related to https://github.com/jenkins-infra/kubernetes-management/pull/2934
- Add the docker image tag in the values of accountapp (now that it's "automatically built") + track it with updateclie (ref. https://github.com/jenkins-infra/helm-charts/issues/64)
- Track the new plugin-health-score 's Docker image tag with updatecli
- Update the updatecli manifests with some 0.33.x improved syntax
> Updatecli: Add/Update manifests to track more elements

- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/templates/service.yaml
- charts/artifact-caching-proxy/values.yaml
To be able to configure AWS NLB annotations
> feat(artifact-caching-proxy): expose service.annotations

- index.yaml
There has been a race condition after the successive merge of #235 and #234, resulting in this commit where we can see only accountapp remained in the helm charts repo index.yaml: https://github.com/jenkins-infra/helm-charts/commit/5aca4f0e811ed4c0a10851637b828b731bc33e24
> fix: restore wiki 0.3.30 in the helm chart repo index

- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/templates/service.yaml
- charts/artifact-caching-proxy/values.yaml
Reverts jenkins-infra/helm-charts#230, not needed at all. (Was for a test around AWS load balancing)
> Revert "feat(artifact-caching-proxy): expose service.annotations"

- updatecli/updatecli.d/mirrorbits.yaml
Ref: https://github.com/jenkins-infra/helm-charts/pull/231
> "[updatecli][githubrelease] Bump version to ✔"
> fix: mirrorbits updatecli pr.title

- updatecli/updatecli.d/ldap.yaml
- updatecli/updatecli.d/mirrorbits.yaml
- updatecli/updatecli.d/uplink.yaml
Same context as https://github.com/jenkins-infra/jenkins-infra/pull/2439.
This PR ensures that the `sha256:  prefix is removed when retrieving dockerdigest
> chore(updatecli) fix manifests with dockerdigest in 0.36.x

- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/templates/nginx-default-configmap.yaml
From https://jenkins.datadoghq.com/integrations/nginx
> Note: The default NGINX log format does not have a request response time.
> feat(artifact-caching-proxy): add response time to nginx logs

- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/templates/statefulset.yaml
The additional ones were never declared.
> fix(artifact-caching-proxy): always add annotations other than podAnnotations

- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/templates/statefulset.yaml
The single quotes present in the values.yaml are lost when applied in the statefulset, rendering this value recognized as an array instead of a string.
> fix(artifact-caching-proxy): single quote around values.logCollectionconfig

- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/values.yaml
Fix datadog agent log error 'Invalid configuration for service: could not parse kubernetes annotation'
> fix(artifact-caching-proxy): fix datadog logs annotation format

- charts/jenkins-kubernetes-agents/Chart.yaml
- charts/jenkins-kubernetes-agents/templates/resourcequota.yaml
- charts/jenkins-kubernetes-agents/tests/defaults_test.yaml
- charts/jenkins-kubernetes-agents/values.yaml
as per : https://github.com/jenkins-infra/helpdesk/issues/3230
as per https://v1-23.docs.kubernetes.io/docs/concepts/policy/resource-quotas/ for now we only implement the max number of pods to match the actual jenkins limit configuration.
> Feat(jenkins-kubernetes-agents): add a resource quota

- charts/plugin-health-scoring/Chart.yaml
- charts/plugin-health-scoring/templates/deployment.yaml
- charts/plugin-health-scoring/values.yaml
Readiness and Liveness have two different endpoints offered by `actuator`.
> feat(plugin-health-scoring): allow specific readiness and liveness probe paths

- .github/workflows/release.yml
> chore(gh workflow) only allow 1 chart release at a time

- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/templates/nginx-proxy-configmap.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/2322
This PR fixes the ACP which are currently responding with HTTP/502.
It introduces the following changes:
- Use the `$request_uri` in the `proxy_pass` directive to  ensure that requested URL are forwarded to the remote upstream
- Make sure that no `Authorization` header is forwarded by cleaning it up (otherwise JFrog answers HTTP/401)
> fix(acp): Correct ACP Nginx setup to fix HTTP/502 errors

- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/templates/nginx-default-configmap.yaml
- charts/artifact-caching-proxy/templates/nginx-proxy-configmap.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/2322
Depends on #396
This PR improves the log management for the ACP proxy:
- Adds upstream related fields in access log to help diagnosing behavior
- Do not log request to nginx status (datadog) or health endpoint (pipeline library and probes)
- (chore) Add explanatory comments while we're there
> feat(acp) improve access logs

- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/templates/nginx-proxy-configmap.yaml
This PR adds the SNAPSHOTS URLs (from our infra to https://repo.jenkins-ci.org/*SNAPSHOT*) in the cached items.
As pointed by @jglick a few weeks ago, this should be fine since SNAPSHOTS have unique names.
> feat(acp) add SNAPSHOT artefacts to caching

- .github/workflows/test.yml
I've noticed this warning on actions, which are (too) frequently failing to download helm-unittest:
> fix(GHA): add GITHUB_TOKEN

- .github/workflows/test.yml
Fixup of #402 
- Warning in #402 's body comes from the `azure/setup-helm` (ref. https://github.com/Azure/setup-helm#example). By specifying a given version (extracted from our Docker Image principal branch with a dummy `curl | grep`), no need for token anymore
- Trying to solve the "helm plugin install" network error by using @lemeurherve 's trick of ... retrying a 2nd time "to be sure".
> chore(gha) Fix helm plugin network errors and helm setup action warning

- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/templates/ingress-health.yaml
- charts/artifact-caching-proxy/tests/custom_values_test.yaml
- charts/artifact-caching-proxy/tests/defaults_test.yaml
- charts/artifact-caching-proxy/values.yaml
Follow-up of https://github.com/jenkins-infra/kubernetes-management/pull/3537
> chore(artifact-caching-proxy): change the default health check path

- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/templates/nginx-default-configmap.yaml
to avoid a double double quotes
> fix(artifact-caching-proxy): correct nginx log format

- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/values.yaml
As we're caching versioned jar which don't change, we can increase the cache retention time.
(edit by dduportal for gh auto links) Ref. https://github.com/jenkins-infra/helpdesk/issues/2752
> chore(artifact-caching-proxy): increase default cache retention to one month

- .github/workflows/release.yml
- .github/workflows/sync-readme.yaml
- .github/workflows/test.yml
Ref: https://github.com/jenkins-infra/helpdesk/issues/3402
> chore: pin GitHub actions with their SHA-1 instead of their version number

- charts/plugin-health-scoring/Chart.yaml
- charts/plugin-health-scoring/values.yaml
In place of #438 without the indentation modifications.
> Bump Plugin Health Scoring from 1.8.0 to 1.9.0

- charts/artifact-caching-proxy/Chart.yaml
First release run failed with:
(https://github.com/jenkins-infra/helm-charts/actions/runs/4605841335)
Second one triggered manually failed as the chart version already existed, hence this bump.
> chore(acp): bump chart version

- .github/workflows/test.yml
- charts/artifact-caching-proxy/tests/defaults_test.yaml
- charts/httpredirector/tests/defaults_test.yaml
- charts/httpredirector/tests/withvalues_test.yaml
- charts/jenkins-jobs/tests/credentials_test.yaml
- charts/jenkins-jobs/tests/defaults_test.yaml
- charts/jenkins-jobs/tests/folders_test.yaml
- charts/jenkins-jobs/tests/multibranch_job_test.yaml
This PR fixes the builds failure, during the unit tests steps, with the `unknown flag: --helm3` error (https://github.com/jenkins-infra/helm-charts/actions/runs/4675170591/jobs/8280015667?pr=480).
It appears that `quintush` has switched back (or was granted maintenership) on https://github.com/helm-unittest/helm-unittest as per https://github.com/quintush/helm-unittest/issues/124.
A commit was added to update the YAML manifest syntax to fulfill the new JsonPath module introduced in https://github.com/helm-unittest/helm-unittest/releases/tag/v0.3.0
> chore(tests) switch from quintush to helm-unittest

- charts/jenkins-kubernetes-agents/Chart.yaml
- charts/jenkins-kubernetes-agents/templates/serviceaccounttoken.yaml
- charts/jenkins-kubernetes-agents/tests/custom_values_test.yaml
- charts/jenkins-kubernetes-agents/tests/defaults_test.yaml
While working on https://github.com/jenkins-infra/helpdesk/issues/3521, I stumbled upon this change in Kubernetes 1.23
This PR ensures that an API token for the `jenkins-agent` SVC account is created: https://v1-24.docs.kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-service-account-api-token.
- SVC accounts created before Kubernetes 1.23 keep their existing token (it's the case for `cik8s`'s `jenkins-agents/jenkins-agent` SVC account)
- If a custom SVC account is specified, then no token is created
Validated with the following:
- Unit tests (of course)
- Verified with local `helmfile diff` commands:
- `jenkins-agents` and `jenkins-agents-bom` releases in `cik8s` cluster: new secret created for each. The former secret for …
> feat(jenkins-kubernetes-agents) add an SVC account token (no longer generated since Kubernetes 1.23)

- charts/accountapp/Chart.yaml
- charts/accountapp/templates/deployment.yaml
Ad quotes around smtp.port value to avoid the error `json: cannot unmarshal number into Go struct field EnvVar.spec.template.spec.containers.env.value of type string`
> fix(accountapp): quote `smtp.port` value

- charts/accountapp/Chart.yaml
- charts/accountapp/templates/deployment.yaml
- charts/accountapp/values.yaml
Follow-up of https://github.com/jenkins-infra/account-app/pull/264
Also set the default SMTP port to 587 as the auth is activated, to respect the default behaviour of the app prior to https://github.com/jenkins-infra/account-app/pull/265
> feat(accountapp): allow configuring the sender email address value

- charts/jenkins-kubernetes-agents/tests/custom_values_test.yaml
Fix the following error seen recently on PRs, ex: https://github.com/jenkins-infra/helm-charts/actions/runs/5055580244/jobs/9071961236
```
FAIL  Tests with custom values	jenkins-kubernetes-agents/tests/custom_values_test.yaml
- Should create a token for the the service account 'jenkins-agent' in the provided namespace
- asserts[0] `hasDocuments` fail
Error:
template "jenkins-kubernetes-agents/templates/serviceaccounttoken.yaml" not exists or not selected in test suite
- asserts[1] `isKind` fail
Error:
template "jenkins-kubernetes-agents/templates/serviceaccounttoken.yaml" not exists or not selected in test suite
- asserts[2] `equal` fail
Error:
template "jenkins-kubernetes-agents/templates/serviceaccounttoken.yaml" not exists or not selected in test suite
- asserts[3] `equal` fail
Error: …
```
> fix(jenkins-kubernetes-agents): add missing templates in the custom value unit test

- .github/workflows/test.yml
- updatecli/updatecli.d/helm-unittest.yaml
This PR pins the helm plugin version used in the GitHub Action workflow to test several charts.
Follow-up of #512 
Set to before last version to check updatecli manifest.
> fix: pin `unittest` helm plugin version

- charts/mirrorbits/Chart.yaml
- charts/mirrorbits/templates/deployment.files.yaml
- charts/mirrorbits/templates/deployment.yaml
As it is currently, even with a `repository.name` value specified in values.yaml, the PVC is named only in the PVC template, it has a generic release name + "-binary" in the deployments templates.
This PR fixes that.
Note: I don't see why there are `$.` in front of some of the `if` in these deployments an in the PVC template 🤔
> fix(mirrorbits): use the PVC name defined in values.yaml everywhere

- .github/workflows/test.yml
- charts/mirrorbits/Chart.yaml
- charts/mirrorbits/tests/default_secrets_values.yaml
- charts/mirrorbits/tests/defaults_test.yaml
This PR adds unit testing to the mirrorbits chart in order to fix the issues I've encountered when working on https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-1660258021 trying to deploy https://github.com/jenkins-infra/kubernetes-management/pull/4211.
The current chart does not pass this basic test as it needs to be fixed with https://github.com/jenkins-infra/helm-charts/pull/585/commits/b2967643d67e3cab10f24b1a76b4066b15838a62.
~Indeed, even if this code block is commented, the template engine tries to retrieve `.Values.resource.mirrorbits`, undefined in the default chart values.~
WTH... It passes here now with helm-unittest 🤔
Anyway, it still fails with helm:
```
$ helm template test ./charts/mirrorbits -f ./charts/mirrorbits/values.yaml -f …
```
> chore(mirrorbits): add unit testing

- .github/workflows/check-chart-versions-bump.yml
This PR fixes the `check-chart-versions-bump` GitHub Action workflow to not fail if the pull request adds a new chart (ie the corresponding `charts/<chart-name>/Chart.yaml` file doesn't exist in the target branch) or if the pull request Chart.yaml version isn't set.
It also refactors the workflow to use a multi jobs mechanism similar to #596 and to run only if there are changes in `./charts/**`.
Tested on a fork.
Example with a new `anewchart` chart and a change in `accountapp` chart for which the version hasn't been bumped:
> Info: charts/anewchart/Chart.yaml doesn't exist or a version can't be read from it on the target branch.
> Info: the version of the 'anewchart' chart has been bumped from '' to '1.2.3'.
> fix(check-chart-versions-bump): don't fail on new chart

- .github/workflows/check-chart-versions-bump.yml
This PR uses only one job intead of a matrix with 2 separate jobs so this GHA check can be set as required in branch protection settings.
Ref: https://github.com/jenkins-infra/helm-charts/issues/596#issuecomment-1686243269
> fix(check-chart-version-bump): use only one job to be able to set it as required

- charts/mirror/.helmignore
- charts/mirror/Chart.yaml
- charts/mirror/README.md
- charts/mirror/templates/NOTES.txt
- charts/mirror/templates/_helpers.tpl
- charts/mirror/templates/configmap.yaml
- charts/mirror/templates/deployment.yaml
- charts/mirror/templates/ingress.yaml
- charts/mirror/templates/persistentVolume.yaml
- charts/mirror/templates/persistentVolumeClaim.yaml
- charts/mirror/templates/secret.yaml
- charts/mirror/templates/service-rsyncd.yaml
- charts/mirror/templates/service-web.yaml
- charts/mirror/templates/tests/test-connection.yaml
- charts/mirror/values.yaml
Restore the `mirror` chart removed in https://github.com/jenkins-infra/kubernetes-management/pull/1604 to use it for a rsync server dedicated to Update Center mirrorbits.
Ref: https://github.com/jenkins-infra/helpdesk/issues/2649
> chore: restore `mirror` chart

- updatecli/updatecli.d/accountapp.yaml
- updatecli/updatecli.d/helm-unittest.yaml
- updatecli/updatecli.d/incrementals-publisher.yaml
- updatecli/updatecli.d/ircbot.yaml
- updatecli/updatecli.d/ldap.yaml
- updatecli/updatecli.d/mirrorbits.yaml
- updatecli/updatecli.d/nginx.yaml
- updatecli/updatecli.d/plugin-health-scoring.yaml
- updatecli/updatecli.d/plugin-site-issues.yaml
- updatecli/updatecli.d/rating.yaml
- updatecli/updatecli.d/rss2twitter.yaml
- updatecli/updatecli.d/uplink.yaml
- updatecli/updatecli.d/wiki.yaml
This PR fixes the following updatecli issues in this repository:
- https://github.com/updatecli/updatecli/releases/tag/v0.57.0 introduces a breaking change in the docker digest sources
- We have a lot of warning about the YAMl resource keys
- Removed the rsyncd manifest as the charts was renamed (feel free to reintroduce a new one once #609 is merged)
Closes #603 #604 #605
> chore(updatecli) remove unused or deprecated manifest content for 0.57.0

- .github/workflows/check-chart-versions-bump.yml
And removed unused job output.
Fixup of #594
> fixup(check-chart-versions-bump): better naming

- charts/mirrorbits/Chart.yaml
- charts/mirrorbits/templates/deployment.rsyncd.yaml
- charts/mirrorbits/templates/ingress.rsyncd.yaml
Ref: https://github.com/jenkins-infra/kubernetes-management/pull/4278#issuecomment-1690112769
> fix(mirrorbits): unique names for rsyncd `deployment` and `ingress` resources

- .github/workflows/check-chart-versions-bump.yml
> fix(check-chart-versions-bump): correct `output` names

- charts/mirrorbits/Chart.yaml
- charts/mirrorbits/templates/configmap.rsyncd.jenkins-motd.yaml
- charts/mirrorbits/templates/configmap.rsyncd.rsyncd-conf.yaml
- charts/mirrorbits/templates/deployment.rsyncd.yaml
- charts/mirrorbits/values.yaml
This PR add the possibility to set the content of https://github.com/jenkins-infra/docker-rsyncd/blob/main/config/rsyncd.conf and https://github.com/jenkins-infra/docker-rsyncd/blob/main/config/jenkins.motd
> feat(mirrorbits): allow setting rsyncd config files content

- charts/mirrorbits/Chart.yaml
- charts/mirrorbits/templates/deployment.rsyncd.yaml
- charts/mirrorbits/values.yaml
- updatecli/updatecli.d/mirrorbits.yaml
The PR https://github.com/jenkins-infra/kubernetes-management/pull/4286 shows that the version `0.61.0` of the `mirrorbits` chart is setting up incorrect container image and tag names:
```diff
containers:
- name: rsyncd
-           image: "jenkinsciinfra/rsyncd@sha256:bc5b180219c491e514234ad1c7274f53cf8161c4be90be86dae9231f843e8417"
+           image: "jenkinsciinfra/rsyncd@sha256:latest@sha256:ab76cbaa200f914d69cce68ee771e40aced3627740796e9e31845d7c883f0a67"
imagePullPolicy: IfNotPresent
ports:
```
https://github.com/jenkins-infra/helm-charts/pull/611 was not enough so let's fix the `mirrorbits` chart
> fix(mirrorbits) correct container image name tag and digest usages

- charts/mirrorbits-lite/Chart.yaml
- charts/mirrorbits-lite/templates/secret.yaml
- charts/mirrorbits-lite/values.yaml
- charts/mirrorbits/Chart.yaml
- charts/mirrorbits/values.yaml
This PR fixes the error encountered when templating mirrorbits(-lite) secret with `helm template charts/mirrorbits`:
> Error: template: mirrorbits/templates/secret.yaml:17:62: executing "mirrorbits/templates/secret.yaml" at <b64enc>: invalid value; expected string
It also removes the conditions in mirrorbits-lite secret, not needed.
> fix(mirrorbits[-lite]): set default empty secret values

- charts/httpd/Chart.yaml
- charts/httpd/templates/secret.yaml
- charts/httpd/values.yaml
This PR fixes the following error:
> Error: template: httpd/templates/secret.yaml:8:24: executing "httpd/templates/secret.yaml" at <.Values.httpd.conf>: nil pointer evaluating interface {}.conf
Keeping mirrorbits chart default value, could probably be improved in a cleanup PR.
> fix(httpd): default httpd.conf value

- .github/workflows/test.yml
No branche returned otherwise.
> fix(gha): correct grep for retrieving all charts to be unittested on main branch

- charts/httpd/Chart.yaml
- charts/httpd/templates/secret.yaml
This PR removes the `httpd.conf` secret, not used as this conf is already defined as configmap, comes from a mistake while extracting the chart from mirrorbits in #641
> fix(httpd): remove unused `httpd.conf` secret

- updatecli/updatecli.d/httpd.yaml
- updatecli/updatecli.d/rsyncd.yaml
Fixes updatecli manifest following up #639 and #641
> chore(updatecli) fix httpd and rsyncd manifest to track their respective charts

- updatecli/updatecli.d/mirrorbits-parent.yaml
> chore(mirrorbits-parent): add updatecli manifest

- .github/workflows/release.yml
Supersedes #677 to fix this error:
https://github.com/jenkins-infra/helm-charts/actions/runs/6111992877/job/16588472488
```
Run helm/chart-releaser-action@be16258da8010256c6e82849661221415f031968
Run owner=$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")
Looking up latest tag...
Discovering changed charts since 'rsyncd-0.0.3'...
Installing chart-releaser on /opt/hostedtoolcache/cr/v1.5.0/x86_64...
Adding cr directory to PATH...
Packaging chart 'charts/mirrorbits-parent'...
Error: no repository definition for https://jenkins-infra.github.io/helm-charts, https://jenkins-infra.github.io/helm-charts, https://jenkins-infra.github.io/helm-charts
Usage:
cr package [CHART_PATH] [...] [flags]
```
> fix(release): add `jenkins-infra` helm repository before running chart-releaser

- updatecli/updatecli.d/rsyncd.yaml
Like the other charts.
Noticed in #683
> chore(updatecli/rsyncd): use `patch` as versionincrement

- charts/rsyncd/Chart.yaml
- charts/rsyncd/templates/configmap.rsyncd-conf.yaml
- charts/rsyncd/templates/deployment.yaml
- charts/rsyncd/templates/service.yaml
- charts/rsyncd/tests/custom_values_test.yaml
- charts/rsyncd/tests/defaults_test.yaml
- charts/rsyncd/values.yaml
While trying to execute `rsyncd` with the new 1.x image (which default user is the unprivileged `nobody`), the `rsync`  process is failing with exit code `10` (I/O error) as caught by @lemeurherve .
After a `strace`, we saw the error `bind(4, {sa_family=AF_INET, sin_port=htons(873), sin_addr=inet_addr("0.0.0.0")}, 16) = -1 EACCES (Permission denied)`: the default port 873 requires privileged access.
This PR fixes the helm chart to use another pod exposed port to bypass this problem: a new value `port` is introduced, defaulted to `1873` (symmetry with the port published by the Kubernetes Service for `rsyncd`).
The `rsync.inc` file is used to override the default setup from the container image.
Note: the custom values specified in the unit test have been factorized to avoid cherry-picking …
> fix(rsyncd) allow running as non root by specifying an internal port > 1024

- charts/rsyncd/Chart.yaml
- charts/rsyncd/templates/deployment.yaml
- charts/rsyncd/tests/defaults_test.yaml
Caught while debugging with @lemeurherve
> cleanup(rsyncd) defer default command to container image

- charts/rsyncd/Chart.yaml
- charts/rsyncd/tests/defaults_test.yaml
- charts/rsyncd/values.yaml
Caught while pairing with @lemeurherve : the mount path should be inside the `/etc/rsyncd.d` directory.
> fix(rsyncd) mount motd in the configuration directory

- updatecli/updatecli.d/wiki.yaml
Please note that this PR won't have any effect until https://github.com/updatecli/updatecli/issues/1582 is fixed and deployed to jenkins infra
> chore(updatecli) fix wiki chart image architecture to use 'arm64'

- charts/mirrorbits/Chart.yaml
- charts/mirrorbits/templates/deployment.yaml
- charts/mirrorbits/tests/custom_values_test.yaml
- charts/mirrorbits/tests/defaults_test.yaml
- charts/mirrorbits/tests/secrets_default_values.yaml
- charts/mirrorbits/values.yaml
While working on https://github.com/jenkins-infra/helpdesk/issues/3136, I had to enable the download logs on mirrorbits.
These logs are written in the container root which is a bad practice (for performance at least).
This PR ensures that the logs directory of mirrorbits deployment is set as a data volume, emptydir by default.
- Added unit tests
- Installed on a local k3s (smoke test only: I haven't checked if the logs are writtenà)
- Tried a helmfile diff with production: it only changes the version in metadata and set the emptydir volume in the pod (no other changes)
(edit after first code review) This PR also updates the "custom values" test harness to factorize the values on top of the file. Not strictly mandatory but it helped me to properly set up my unit test case (as part of TDD …
> feat(mirrorbits) use a volume for logs

- charts/mirrorbits/Chart.yaml
- charts/mirrorbits/templates/deployment.yaml
- charts/mirrorbits/tests/custom_values_test.yaml
- charts/mirrorbits/tests/defaults_test.yaml
TL;DR;
`s#/var/logs/#/var/log` because /me was not paying attention 🥲
> fix(mirrorbits) correct the mountpath to the real location 

- charts/mirrorbits-parent/Chart.yaml
- charts/mirrorbits-parent/README.md
- charts/mirrorbits-parent/templates/_helpers.tpl
- charts/mirrorbits-parent/templates/persistentvolumesecret.yaml
- charts/mirrorbits-parent/values.yaml
as per https://github.com/jenkins-infra/helm-charts/pull/774 post-merge review
- Adds a `README.md` documentating the umbrellas ingress and storages
- Fully comment out the `storage.persistentVolume.azureFile` value to avoid confusion
- Update helper template comments
> docs(mirrorbit-parents) improve documentation

- charts/accountapp/Chart.yaml
- charts/accountapp/templates/deployment.yaml
- charts/accountapp/tests/custom_values_test.yaml
- charts/accountapp/tests/defaults_test.yaml
- charts/accountapp/values.yaml
Thanks @olblak for catching the root issue ❤️ 
This PR fixes an issue when using the default value for `resources` which should be `{}` to ensure all YAML parser consider it as null.
Please note that I have a personal preference for commenting out the empty or undefined values on helm charts, but this fix will do.
> fix(account-app) correct default values for 'resources' to avoid YAML parsing error

- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/templates/nginx-proxy-configmap.yaml
- charts/artifact-caching-proxy/tests/proxy_cache_bypass_test.yaml
- charts/artifact-caching-proxy/values.yaml
This PR adds the ability to selectively refresh cached elements.
Inspiration taken from https://bluegrid.io/edu/how-to-purge-the-nginx-cache
> Add optional selective cache refresh option

- charts/jenkinsio/Chart.yaml
- charts/jenkinsio/tests/custom_values.yaml
- charts/jenkinsio/tests/defaults_values_test.yaml
- charts/jenkinsio/values.yaml
While working on https://github.com/jenkins-infra/kubernetes-management/pull/4430 we needed to fix this to have unit tests.
Closes  #658
> fix(jenkinsio) ensure default values are valid. Closes #658.

- charts/httpd/Chart.yaml
- charts/httpd/templates/_helpers.tpl
- charts/httpd/templates/deployment.yaml
- charts/httpd/templates/ingress.yaml
- charts/httpd/templates/mocks/_helpers.tpl
- charts/httpd/templates/persistentVolume.yaml
- charts/httpd/templates/persistentVolumeClaim.yaml
- charts/httpd/tests/custom_values_test.yaml
- charts/httpd/tests/defaults_test.yaml
- charts/httpd/tests/parent_values_test.yaml
Same as https://github.com/jenkins-infra/helm-charts/pull/817 but for httpd
> feat(httpd) allow overriding ingress and PV(C)s based on global value from parent chart

- charts/uplink/Chart.yaml
- charts/uplink/templates/_helpers.tpl
- charts/uplink/templates/deployment.yaml
- charts/uplink/templates/pdb.yaml
- charts/uplink/tests/custom_values_test.yaml
- charts/uplink/tests/defaults_test.yaml
- charts/uplink/values.yaml
> feat(uplink): add PodDisruptionBudget and unittests

- charts/reports/Chart.yaml
- charts/reports/templates/_helpers.tpl
- charts/reports/templates/deployment.yaml
- charts/reports/templates/pdb.yaml
- charts/reports/tests/custom_values_test.yaml
- charts/reports/tests/defaults_values_test.yaml
- charts/reports/values.yaml
> feat(reports): add PodDisruptionBudget and unittests

- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/tests/custom_values_test.yaml
- charts/artifact-caching-proxy/values.yaml
This PR fixes the error seen in https://github.com/jenkins-infra/kubernetes-management/pull/4460#pullrequestreview-1649313575 
```
[ERROR] templates/: template: artifact-caching-proxy/templates/pdb.yaml:9:18: executing "artifact-caching-proxy/templates/pdb.yaml" at <.Values.poddisruptionbudget.minAvailable>: nil pointer evaluating interface {}.minAvailable
```
💡Notes:
- Unit test added to cover the case when a PDB is created because multiple replicas are set up but with its default setup. This unit tests returns the error above with the version `0.15.0` of this chart
- Unit test added to verify the coverage of custom value `maxUnavailable`
> fix(artifact-caching-proxy) set defaults on PDB

- charts/httpd/.helmignore
- charts/httpd/Chart.yaml
- charts/httpd/templates/_helpers.tpl
- charts/httpd/templates/mocks/_helpers.tpl
- charts/httpd/tests/parent_values_test.yaml
- charts/mirrorbits-lite/.helmignore
- charts/mirrorbits-lite/Chart.yaml
- charts/mirrorbits-lite/templates/_helpers.tpl
- charts/mirrorbits-lite/templates/mocks/_helpers.tpl
- charts/mirrorbits-lite/tests/parent_values_test.yaml
This PR is a fixup of #817 and #818.
These past PRs did not break the current `update-jenkins-io` *but* the new feature to use global PVC/ingress from parent chart had some hiccups.
Namely, the mocks used for unit tests are packaged with the subchart and adding the pattern `*mock*` to the [`.helmignore`](https://helm.sh/docs/chart_template_guide/helm_ignore_file/) results in unit test failing because, with the current 0.3.5 version of unit tests, it does not access files ignores by the`.helmignore`.
The result is, when trying on real life, the mocked templates takes over the expected template from the parent chart leading to unexpected results.
The proposed solution (2 commits, 1 per chart) proposes to use a combination of:
- An idea by @lemeurherve around passing the PVC name through the …
> fixup(httpd & mirrorbits-lite) remove all mocks from packaged chart

- charts/rsyncd/.helmignore
- charts/rsyncd/Chart.yaml
- charts/rsyncd/templates/_helpers.tpl
- charts/rsyncd/templates/deployment.yaml
- charts/rsyncd/tests/parent_values_test.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/2649
Same idea as #817 and #818 , this PR allows passing template in rsync component definitions, for dynamic evaluation of the PVC name.
> feat(rsyncd) allow overriding PV(C)s based on global value from parent chart

- charts/plugin-site/Chart.yaml
- charts/plugin-site/templates/_helpers.tpl
- charts/plugin-site/templates/deployment-frontend.yaml
- charts/plugin-site/templates/pdb-frontend.yaml
- charts/plugin-site/tests/custom_values_test.yaml
- charts/plugin-site/tests/defaults_values_test.yaml
- charts/plugin-site/values.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3719
```
plugin-site, plugin-site-frontend, PodDisruptionBudget (policy) has been added:
- 
+ # Source: plugin-site/templates/pdb-frontend.yaml
+ apiVersion: policy/v1
+ kind: PodDisruptionBudget
+ metadata:
+   name: plugin-site-frontend
+   labels:
+     app.kubernetes.io/name: plugin-site
+     app.kubernetes.io/instance: plugin-site
+     helm.sh/chart: plugin-site-0.3.0
+     app.kubernetes.io/version: "1.0"
+     app.kubernetes.io/managed-by: Helm
+     jenkins.io/maintainer: timja
+ spec:
+   minAvailable: 1
+   selector:
+     matchLabels:
+       app.kubernetes.io/name: plugin-site-frontend
+       app.kubernetes.io/instance: plugin-site
```
> feat(plugin-site-frontend): add PDB and unittest

- charts/mirrorbits-lite/.helmignore
- charts/mirrorbits-lite/Chart.yaml
- charts/mirrorbits-lite/templates/deployment.yaml
- charts/mirrorbits-lite/templates/secrets.yaml
- charts/mirrorbits-lite/tests/custom_values_test.yaml
- charts/mirrorbits-lite/tests/defaults_test.yaml
- charts/mirrorbits-lite/tests/parent_values_test.yaml
While working on the parent chart for https://github.com/jenkins-infra/helpdesk/issues/2649, caught this tiny bug in the helm chart where secrets where created even if values are not provided.
This PR fixes the bug by adding conditions to create the secrets (and tests).
> fix(mirrorbit-lite) only create secrets when needed

- charts/plugin-site/Chart.yaml
- charts/plugin-site/values.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3774, this PR bumps the container image to a new version with a JDK Temurin version `1.8.0_382`.
The goal is to only deploy the JDK change to support cgroups v2 in production.
We did a quick test on a Docker Desktop macOS machine (which uses cgroupsv2 in the LinuxVM) with success:
- The Docker Desktop VM is set up with 16Gb of memory
- The default heap size is 25% of what is perceived by the JVM as "the amount of memory available to use"
Before (current production image) states ~4Gb of Heap despite the specified memory limit at 1G:
```bash
$ docker run --entrypoint=bash --platform=linux/amd64 --memory=1G jenkinsciinfra/plugin-site-api:294-5389ef -c 'java -XX:+PrintFlagsFinal -version | grep HeapSize'
openjdk version "1.8.0_322" …
```
> fix(plugin-site) bump Docker image to switch JDK8 to Temurin `1.8.0_382` (and support of cgroups v2)

- charts/rating/Chart.yaml
- charts/rating/templates/deployment.yaml
- charts/rating/tests/defaults_test.yaml
- Fix #661
- `{{- if ~~ -}}` will be render inappropriately (ref: https://helm.sh/docs/chart_template_guide/control_structures/#controlling-whitespace)
- remove trailing `-`, so it renders well.
- Add simple unit test to ensure rendering.
- original `deployment.yaml`
- ![image](https://github.com/jenkins-infra/helm-charts/assets/16630665/97c45092-4262-416e-8102-d72ba398c875)
- fixed version
- ![image](https://github.com/jenkins-infra/helm-charts/assets/16630665/0e46eafc-ae64-47fd-8bb9-21f353c0839c)
> Fix `rating` chart render issue and add unit tests

- charts/mirrorbits-parent/Chart.yaml
- charts/mirrorbits-parent/templates/_helpers.tpl
- charts/mirrorbits-parent/templates/serviceaccount.yaml
- charts/mirrorbits-parent/tests/custom_values_serviceaccount_test.yaml
- charts/mirrorbits-parent/tests/defaults_test.yaml
- charts/mirrorbits-parent/values.yaml
as per https://github.com/jenkins-infra/update-center2/pull/745#issuecomment-1778674192
and for https://github.com/jenkins-infra/helpdesk/issues/2649
this provide a Service Account for the mirrorbits parents helm chart
> feat (mirrorbits-parents): add service account

- charts/uplink/Chart.yaml
- charts/uplink/values.yaml
- updatecli/updatecli.d/uplink.yaml
Using a sha256 blocks the deployment of the arm64 image by the chart, thus this PR switch to the named tag instead of the sha256 in the values.
Related:
- https://github.com/jenkins-infra/kubernetes-management/pull/4610
Note: the image specs override in kubernetes-management has been removed:
- https://github.com/jenkins-infra/kubernetes-management/pull/4607
> fix(uplink): use tag instead of sha256 for the Docker image

- charts/mirrorbits-parent/Chart.yaml
- charts/mirrorbits-parent/templates/serviceaccount.yaml
- charts/mirrorbits-parent/tests/custom_values_serviceaccount_test.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-1787324647
Tested on a k3d local cluster: no need for addition permissions other than this one
> fix(mirrorbit-parent) add missing permission to allow exec on a pod

- updatecli/updatecli.d/httpd.yaml
- updatecli/updatecli.d/incrementals-publisher.yaml
- updatecli/updatecli.d/nginx.yaml
- updatecli/updatecli.d/rating.yaml
- updatecli/updatecli.d/wiki.yaml
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3619
> chore(updatecli): ensure every arm64 migrated service manifest is checking for arm64 image too

- charts/httpd/Chart.yaml
- charts/httpd/values.yaml
- charts/httpredirector/Chart.yaml
- updatecli/updatecli.d/httpd.yaml
Using a sha256 blocks the deployment of the arm64 image by the chart, thus this PR removes the sha256 from the tag values.
Similar to:
- https://github.com/jenkins-infra/helm-charts/pull/903
Related:
- https://github.com/jenkins-infra/kubernetes-management/pull/4586
Closes #913 
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3619
> fix(httpd): don't include sha256 in `image.tag` value

- .github/workflows/check-chart-versions-bump.yml
- .github/workflows/test.yml
This PR removes the `on.*.paths` from workflows set as required status checks in branch protections.
These workflows already check if there are charts modified, and currently this prevents merging pull requests without bypassing branch protections if they don't contain changes to the `charts` folder.
- https://github.com/jenkins-infra/helm-charts/pull/912
> chore(GHA): remove `on.*.paths` from required workflows

- updatecli/updatecli.d/httpd.yaml
Follow-up of https://github.com/jenkins-infra/helm-charts/pull/915 for `mirrorbits` original chart, to allow its `httpd` "files" service to be deployed on arm64.
Related:
- https://github.com/jenkins-infra/kubernetes-management/pull/4586
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3619
> chore(updatecli): also target `httpd` image version without sha256 in `mirrorbits` chart

- charts/httpd/Chart.yaml
- charts/httpd/templates/configmap.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/2649
This PR updates the default `httpd` configuration to be tailored to the Jenkins mirrorbits usage as it is the only known usage.
It is a "short term" fix to ensure we can get started with the new Update Center using the `mirrorbits-parent` chart.
A long term fix would be either to add a feature to `httpd` chart to specify its custom conf through confimap setup, or even better: switch to bitnami's `httpd` chart to benefit from other production ready behaviors (read only, non root, etc.).
> feat(httpd) tailor configuration for Jenkins's mirrorbits usage

- charts/ldap/Chart.yaml
- charts/ldap/templates/service.yaml
- charts/ldap/tests/custom_values_test.yaml
- charts/ldap/tests/defaults_values_test.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3683#issuecomment-1798182954
Checked on the production with the following values:
```
service:
type: LoadBalancer
azurePip:
name: ldap-jenkins-io-ipv4
resourceGroup: prod-public-ips
whitelisted_sources:
```
result is:
```
ldap, ldap, Service (v1) has changed:
...
labels:
app.kubernetes.io/name: ldap
-     helm.sh/chart: ldap-0.2.1
+     helm.sh/chart: ldap-0.3.0
app.kubernetes.io/instance: ldap
app.kubernetes.io/managed-by: Helm
+   annotations:
+     service.beta.kubernetes.io/azure-pip-name: ldap-jenkins-io-ipv4
+     service.beta.kubernetes.io/azure-load-balancer-resource-group: prod-public-ips
spec:
type: LoadBalancer
-   loadBalancerIP: 20.7.180.148
loadBalancerSourceRanges:
- "20.85.71.108/32"
```
> feat(ldap) allow customization of the LB service for Azure

- charts/ipv6-lb-service/Chart.yaml
- charts/ipv6-lb-service/templates/ipv6-lb-service.yaml
- charts/ipv6-lb-service/values.yaml
Blocks https://github.com/jenkins-infra/kubernetes-management/pull/4647
tested locally with ipv6-lb-service charts version 1.0.0 :
```
service.beta.kubernetes.io/azure-load-balancer-internal: "false"
-     service.beta.kubernetes.io/azure-load-balancer-ipv6: "2603:1030:408:5::15a"
+     service.beta.kubernetes.io/azure-pip-name: "public-publick8s-ipv4"
+     service.beta.kubernetes.io/azure-load-balancer-resource-group: prod-public-ips
labels:
app.kubernetes.io/component: controller
```
> feat!(ipv6LBservice): change annotations for azurepipname and ResourceGroup

- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/templates/statefulset.yaml
- charts/artifact-caching-proxy/tests/custom_values_test.yaml
- charts/artifact-caching-proxy/tests/defaults_test.yaml
- charts/artifact-caching-proxy/values.yaml
Adds optional `env` and `envFrom` sections to chart
This allows us to further configure the nginx proxy.
> [artifact-caching-proxy] Add optional `env` and `envFrom` sections

- charts/rsyncd/Chart.yaml
- charts/rsyncd/values.yaml
- updatecli/updatecli.d/rsyncd.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3619#issuecomment-1816831551
and https://github.com/jenkins-infra/kubernetes-management/pull/4691
> feat(rsyncd): remove the sha corresponding to amd64 to enable arm64 images

- .github/workflows/release.yml
Looking at last release GHA builds like https://github.com/jenkins-infra/helm-charts/actions/runs/6932409633, we can see the following error:
> Error while fetching latest Helm release: Error: [@octokit/auth-action] `GITHUB_TOKEN` variable is not set. It must be set on either `env:` or `with:`. See https://github.com/octokit/auth-action.js#createactionauth. Using default version v3.9.0
This PR fixes this by passing the GitHub token as recommended by the GHA documentation in case we're fetching the 'latest' helm release: https://github.com/Azure/setup-helm#example
It also increase the version precision to v3.5 (the current pinned version).
> chore(gha/release): pass GitHub Token to `azure/setup-helm` and increase its version precision

- .github/workflows/release.yml
This PR adds the last commit subject as changelog to each chart GitHub release if they've just been released.
Tested on a fork, example:
- Commit: https://github.com/lemeurherve/helm-charts/commit/5330ffac3c7c195f5f33be412b0f66ba3accfdc2
- Release: https://github.com/lemeurherve/helm-charts/releases/tag/basic-helm-chart-example-1.2.3
> feat(gha/release): add commit subject as chart release changelog

- charts/mirrorbits-parent/Chart.lock
- charts/mirrorbits-parent/Chart.yaml
- charts/mirrorbits-parent/README.md
- charts/mirrorbits-parent/templates/_helpers.tpl
- charts/mirrorbits-parent/tests/custom_values_ingress_test.yaml
- charts/mirrorbits-parent/tests/custom_values_serviceaccount_test.yaml
- charts/mirrorbits-parent/values.yaml
- updatecli/updatecli.d/httpd.yaml
Follow up of #1006 since https://github.com/jenkins-infra/helm-charts/releases/tag/mirrorbits-2.0.0 has been released.
> cleanup!(mirrorbit-parent) change dependency to support renaming of `mirrorbits-lite` to `mirrorbits`. BREAKING.

- charts/mirrorbits-parent/Chart.yaml
- charts/mirrorbits-parent/tests/custom_values_ingress_test.yaml
- charts/mirrorbits-parent/tests/custom_values_storage_test.yaml
- charts/mirrorbits-parent/tests/values/custom.yaml
PR #1011 bumped the helm unittests plugin to [`v0.4.1`](https://github.com/helm-unittest/helm-unittest/releases/tag/v0.4.1).
This version bump made the unittest failing for `mirrorbits-parent` due to https://github.com/helm-unittest/helm-unittest/pull/267: we cannot use "test-scoped" values defined inline with the `set` keyword.
This PR uses a common values files which has the benefit to avoid scattering values over time AND can be overridden per sub test.
Note @lemeurherve , the PR 1011 did not run any check as it detected no chart modification. Do you think it is possible (and easy) to run all unittests if the file in charge of installing the plugin (such as the GHA workflow) is changed?
> chore(mirrorbits-parent) fix unittest for helm-unittest `v0.4.1`

- .github/workflows/test.yml
From #1013:
> [...] the PR #1011 did not run any check as it detected no chart modification. Do you think it is possible (and easy) to run all unittests if the file in charge of installing the plugin (such as the GHA workflow) is changed?
This PR fixes that.
> chore(GHA/test): run tests on all charts if this workflow is modified

- .github/workflows/test.yml
- updatecli/updatecli.d/mirrorbits-parent.yaml
This PR fixes the test.yaml GHA. Tested by cherry-picking #1017 then #1019 commits, both got their checks passing.
Supersedes and closes #1017 
Ref:
- https://github.com/jenkins-infra/helm-charts/pull/1017#issuecomment-1886623791
> fix(GHA/test): don't fail

- .github/workflows/test.yml
This PR properly initialize the `modifiedWorkflow` variable with an empty string if there is no match.
(Still not sure why this fails here and not in other similar lines which can also be empty 🤷)
Tested extensively on my fork.
Fixup of:
- #1014 
- #1020
> fix(GHA/test): proper `modifiedWorkflow` init if empty

- charts/incrementals-publisher/Chart.yaml
- charts/incrementals-publisher/templates/deployment.yaml
- charts/incrementals-publisher/tests/custom_values_test.yaml
- charts/incrementals-publisher/tests/defaults_test.yaml
- charts/incrementals-publisher/tests/secret-values.yaml
- charts/incrementals-publisher/values.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3955
This PR introduces a new feature on the `incrementals-publisher` chart: the permissions URL can be specified through helm values (to override the default value in the app through environment variable).
- Unit tested (of course)
- Tested with a local k3s cluster and 2 scenarios:
- Cluster creation:
<details>
<summary>Click me to expand and view details</summary>
```bash
$ cat .tmp/k3d.yaml 
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
name: jenkins-infra
servers: 1
agents: 2
image: rancher/k3s:v1.26.13-k3s2
ports:
- port: 80:80
nodeFilters:
- loadbalancer
- port: 443:443
nodeFilters:
- loadbalancer
- port: 8080:8080
nodeFilters:
- loadbalancer
options:
k3s:
extraArgs:
- arg: "--disable=traefik"
nodeFilters:
- server:*
$ …
```
> feat(incrementals-publisher) allow customizing permissions URL

- charts/jenkins-jobs/Chart.yaml
- charts/jenkins-jobs/templates/_helpers.tpl
- charts/jenkins-jobs/tests/folders_test.yaml
- charts/jenkins-jobs/tests/multibranch_job_test.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/2778#issuecomment-1959565465
This PR proposes the following:
GitHub checks default notification is changed from `continuous-integration/jenkins/pr-merge` to the following pattern:
`jenkins/<Jenkins FQDN>/<Full Job Identifier>` where:
- <Jenkins FQDN> is passed by helm values or defaults to "localhost"
- <Full Job Identifier> is automatically set to the full Jenkins internal Job ID (string with '/' separators when recursive job structure such as folders or multibranch jobs)
Example with a diff on the infra.ci.jenkins.io setup:
- Principal job for jenkins-infra/packer-images:
```diff
+                       gitHubNotificationContextTrait {
+                         contextLabel('jenkins/infra.ci.jenkins.io/infra-tools/packer-images')
+ …
```
>  feat(jenkins-jobs) add GitHub scm custom notification to ensure distinct checks for each job

- charts/jenkinsio/Chart.yaml
- charts/jenkinsio/templates/deployment.yaml
- charts/jenkinsio/templates/secret.yaml
- charts/jenkinsio/templates/zh-deployment.yaml
While working on jenkins.io storage account replacement, I noticed that some refs are hardcoded, and prevent deploying this chart under another release name than `jenkinsio`. This PR fixes that.
Related:
- https://github.com/jenkins-infra/helpdesk/issues/3414#issuecomment-1961011896
> fix(jenkins.io): don't hardcode `jenkinsio` resource name and references

- charts/jenkinsio/Chart.yaml
- charts/jenkinsio/templates/configmap.yaml
- charts/jenkinsio/templates/deployment.yaml
- charts/jenkinsio/templates/pdb.yaml
- charts/jenkinsio/templates/secret.yaml
- charts/jenkinsio/templates/service.yaml
- charts/jenkinsio/templates/zh-configmap.yaml
- charts/jenkinsio/templates/zh-deployment.yaml
- charts/jenkinsio/templates/zh-pdb.yaml
- charts/jenkinsio/templates/zh-secret.yaml
- charts/jenkinsio/templates/zh-service.yaml
- charts/jenkinsio/tests/custom_values_test.yaml
- charts/jenkinsio/tests/defaults_values_test.yaml
- charts/jenkinsio/values.yaml
This PR allows disabling the deployment of the international or the chinese version of the website.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3414#issuecomment-1961011896
- https://github.com/jenkins-infra/helpdesk/issues/3379
> feat(jenkins.io): allow disabling either jenkins.io or zh-jenkins.io

- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/templates/nginx-proxy-configmap.yaml
- charts/artifact-caching-proxy/tests/defaults_test.yaml
- charts/artifact-caching-proxy/tests/proxy_cache_config_test.yaml
The goal is to improve build performances by:
- Caching Maven central artifacts in ACP along with Jenkins artefacts
- Delegate the chain of "retries" to Nginx (instead of Maven) for efficient caching
- Tune the network behavior by disabling IPv6 DNS resolution and using default Nginx timeouts
The fallback setup is defined statically in the ConfigMap. Possible improvement would be to templatize the chain of fallbacks. For this version the chain is the following: "Jenkins public repo" -> "Jenkins incrementals repo" -> "Maven Central repo".
Notes:
- The number of possible fallbacks is limited internally in Nginx to 10 (ref. http://nginx.org/en/docs/http/ngx_http_core_module.html#recursive_error_pages)
- The non-cached requests (maven-metadata.xml files) are also chained on their own using …
> feat!(artifact-caching-proxy) introduces repository fallbacks chain

- charts/jenkins-jobs/Chart.yaml
- charts/jenkins-jobs/tests/credentials_test.yaml
- charts/jenkins-jobs/values.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3954
This PR is a non-functional change to remove references to the deleted EKS cluster `cik8s`.
Note these references where only comments or tests.
> cleanup(jenkins-jobs) remove references to cik8s deleted cluster

- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/templates/nginx-proxy-configmap.yaml
- charts/artifact-caching-proxy/tests/proxy_cache_config_test.yaml
- charts/artifact-caching-proxy/values.yaml
This PR makes the initial proxy location path configurable.
The chart version has been set, anticipating #1168 being merged first.
> make first proxy target path configurable

- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/templates/nginx-proxy-configmap.yaml
- charts/artifact-caching-proxy/tests/proxy_cache_config_test.yaml
- charts/artifact-caching-proxy/values.yaml
This PR makes the dns resolver IP configurable since some people have their own DNS servers.
- Allow configuration of dns resolver
- Bump chart version for new feature
> make dns resolver configurable

- charts/jenkins-jobs/Chart.yaml
- charts/jenkins-jobs/templates/_helpers.tpl
- charts/jenkins-jobs/tests/multibranch_job_test.yaml
- charts/jenkins-jobs/values.yaml
This PR allows configuring excluded branch pattern for jobs.
Example of use-case: not running pipeline dedicated to PR previews on primary branch.
Ref:
- https://github.com/jenkins-infra/kubernetes-management/pull/5345
> feat(jenkins-jobs): allow defining excluded branch pattern

- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/templates/statefulset.yaml
- charts/artifact-caching-proxy/tests/custom_values_test.yaml
- charts/artifact-caching-proxy/tests/defaults_test.yaml
- charts/artifact-caching-proxy/values.yaml
While working on https://github.com/jenkins-infra/helpdesk/issues/3837, we've been stucked with specifying existing PV for the ACP statefulset.
See https://github.com/jenkins-infra/azure/pull/775#issuecomment-2210796493
As per https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/preexisting-pd#pv_to_statefulset, we can determine the name of the PVCs in advance so we can specify the binding PV <-> PVC on the PV side (in Terraform) using the `claimRef` attribute.
As such, this PR allows customizing the prefix used by Statefulset to generate the PVC names.
Tested against production with the following `helmfile diff`:
```diff
persistence:
-  storageClass: managed-csi-premium-retain
+  enabled: true
+  size: 32
+  storageClass: statically-provisionned
+  # Deterministic …
```
> feat(artifact-caching-proxy) allow customization of the PVC template prefix (for statefulset)

- charts/ldap/Chart.yaml
- charts/ldap/templates/persistentVolume.yaml
- charts/ldap/templates/persistentVolumeClaim.yaml
- charts/ldap/templates/statefulset.yaml
- charts/ldap/tests/custom_values_test.yaml
- charts/ldap/tests/defaults_values_test.yaml
- charts/ldap/values.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3837
This PR introduces ability to specify custom PVCs for data and backup volumes
> feat(ldap) allow specifying custom PVC for data or backup volumes

- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/templates/statefulset.yaml
- charts/artifact-caching-proxy/tests/custom_values_test.yaml
- charts/artifact-caching-proxy/tests/defaults_test.yaml
Fix errors like 
```
Warning  FailedCreate      2m11s (x27 over 29m)  statefulset-controller  create Pod artifact-caching-proxy-0 in StatefulSet artifact-caching-proxy failed error: Pod "artifact-caching-proxy-0" is invalid: [spec.containers[0].volumeMounts[3].name: Not found: "nginx-cache", spec.initContainers[0].volumeMounts[0].name: Not found: "nginx-cache"]
```
> fix(acp) correct missing references to templatized volume in volumeMounts

- charts/httpd/Chart.yaml
- charts/httpd/templates/configmap.yaml
- charts/httpd/tests/custom_values_test.yaml
- charts/httpd/values.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2255522243
BREAKING CHANGE: The `httpdConf` value is replaced by the `httpdConf.override` value.
> feat!(httpd) allow specifying a custom ServerName through the `httpdConf.serverName` new value.

- charts/jenkins-jobs/Chart.yaml
- charts/jenkins-jobs/templates/_helpers.tpl
- charts/jenkins-jobs/tests/folders_test.yaml
- charts/jenkins-jobs/tests/multibranch_job_test.yaml
BREAKING CHANGE: Unless you specify a custom retention policy with the `orphanedItemStrategyDaysToKeep` and `orphanedItemStrategyNumToKeep`, the orphaned items will be disposed as soon as scanning detects the reference is gone.
> feat!(jenkins-jobs) defaults Multibranch Jobs to remove orphaned items immediately and abord their builds.

- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/templates/service.yaml
- charts/artifact-caching-proxy/tests/custom_values_test.yaml
- charts/artifact-caching-proxy/tests/defaults_test.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4204
This PR allows passing custom Service annotations if we do not want to use a `ClusterIP` default service for ACP
> feat(acp) allow specifying annotations for ACP Service

- charts/mirrorbits-parent/Chart.yaml
- charts/mirrorbits-parent/templates/additional-ingresses.yaml
- charts/mirrorbits-parent/tests/custom_values_ingress_test.yaml
- charts/mirrorbits-parent/tests/values/custom.yaml
- charts/mirrorbits-parent/values.yaml
As per https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2284762944, we need to specify 2 ingress objects to support routing in the case of updates.jenkins.io, but not for get.jenkins.io.
This PR introduces a new `ingress.additionalIngresses` value to supply multiple additional ingresses definitions to the `mirrorbits-parent` chart.
Tested locally (unit test + k3d) and on production with the following PR: https://github.com/jenkins-infra/kubernetes-management/pull/5536
> feat(mirrorbits-parent) allow creating addition ingresses to support advanced routing cases

- charts/mirrorbits/Chart.yaml
- charts/mirrorbits/templates/NOTES.txt
- charts/mirrorbits/templates/_helpers.tpl
- charts/mirrorbits/templates/deployment.yaml
- charts/mirrorbits/templates/secrets.yaml
- charts/mirrorbits/templates/service.yaml
- charts/mirrorbits/tests/custom_values_test.yaml
- charts/mirrorbits/tests/defaults_test.yaml
- charts/mirrorbits/tests/parent_values_test.yaml
- charts/mirrorbits/tests/values/custom.yaml
- charts/mirrorbits/tests/values/global.yaml
- charts/mirrorbits/values.yaml
It introduces a new `config` top-level value with a set of default values mapping to mirrorbit reference configuration. Implementation shifts from a Secret to a ConfigMap.
Note that this ConfigMap could hold a Redis password but RBAC allows reading it in clear if you can exec to the container so the secret does not protect more than ConfigMap.
BREAKING CHANGE: the value `conf` is deprecated and ignored. Check the new `config` value instead.
BREAKING CHANGE: the value `logs` is deprecated and ignored. Check the new `config.logs` value instead.
> feat!(mirrorbits) define mirrorbits.conf using (visible) values

- charts/geoipupdates/Chart.yaml
- charts/geoipupdates/templates/_helpers.tpl
- charts/geoipupdates/templates/deployment.yaml
- charts/geoipupdates/templates/secret.yaml
- charts/geoipupdates/tests/defaults_test.yaml
- charts/geoipupdates/values.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4240, this PR introduces a new chart `geoipupdates` which role is to run a centralized instance of maxmind/geoipupdates
> feat(geoipupdates) introduces new chart in version 0.0.1

- updatecli/updatecli.d/geoipupdates.yaml
- updatecli/updatecli.d/mirrorbits.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4240
Follow up of #1273 
This PR tracks the maxmind/geoipupdates version for the new GHCR Docker image in the new geoipupdates charts only, and no more on mirrorbits!
> chore(updatecli) track maxmind/geoipupdates from ghcr.io and only on the new chart

- .github/workflows/release.yml
Fixes the warning message `Warning: Input 'token' has been deprecated with message: GitHub token is no longer required` found (example: https://github.com/jenkins-infra/helm-charts/actions/runs/10430641720/job/28889414774#step:4:1)
> chore(GHA/release.yml) remove deprecated input of `setup-helm` action

- charts/mirrorbits/Chart.yaml
- charts/mirrorbits/templates/deployment.yaml
- charts/mirrorbits/tests/custom_values_test.yaml
- charts/mirrorbits/tests/defaults_test.yaml
- charts/mirrorbits/tests/values/custom.yaml
- charts/mirrorbits/values.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2294769030
In order to have datadog collecting logs, we need to specify annotation for the Deployment's Pod template as per https://docs.datadoghq.com/containers/kubernetes/log/?tab=helm#example-log-autodiscovery-annotations.
> feat(mirrorbits) allow passing annotations to pod template

- charts/mirrorbits/Chart.yaml
- charts/mirrorbits/templates/_helpers.tpl
- charts/mirrorbits/templates/deployment.yaml
- charts/mirrorbits/tests/defaults_test.yaml
- charts/mirrorbits/values.yaml
Logs are enabled by default but may quickly fill the default emptyDir volume. In order to have proper logs rotation, let's use stdout (in addition to current logs). It uses a symlink from the image in /var/log/mirrorbits/download.logs to stdout.
BREAKING CHANGE: No more logs volume and download logs are sent to the stdout.
> feat!(mirrorbits) defaults download logs to stdout

- charts/nginx-website/Chart.yaml
- charts/nginx-website/templates/deployment.yaml
- charts/nginx-website/templates/nginx-configmap.yaml
- charts/nginx-website/tests/custom_values_test.yaml
- charts/nginx-website/tests/defaults_test.yaml
- charts/nginx-website/values.yaml
This PR allows to customise nginx configuration so we can set for example a `try_files` directive, required for React applications for direct links. 
It also sets the port in deployment.yaml to `service.port` in order to use the same value in every template.
Note: I've kept current values to avoid breaking existing releases using this chart, these default values could be updated to more sensible ones like `server_name _;` in the future.
Ref:
- https://github.com/jenkins-infra/stats.jenkins.io/issues/118
- https://github.com/jenkins-infra/helpdesk/issues/4132#issuecomment-2298635602
> feat(nginx-website): allow to customise nginx configuration

- charts/jenkins-jobs/Chart.yaml
- charts/jenkins-jobs/templates/_helpers.tpl
- charts/jenkins-jobs/tests/credentials_test.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4165#issuecomment-2304081117
The `owner()` function in a GH App credential JobDSL definition must be a string. Otherwise it is considered a Groovy reference and any special character is treated as a Groovy operator (such as the `-` of `jenkins-infra`...).
> fix(jenkins-jobs) GH App credential owner must be a groovy string

- charts/mirrorbits/Chart.yaml
- charts/mirrorbits/templates/NOTES.txt
- charts/mirrorbits/templates/deployment.yaml
- charts/mirrorbits/tests/custom_values_test.yaml
- charts/mirrorbits/tests/defaults_test.yaml
While reviewing, I realized that I forgot the probes in https://github.com/jenkins-infra/helm-charts/pull/1268
> fix(mirrorbits) probes should use the specified exposed port

- charts/jenkins-jobs/Chart.yaml
- charts/jenkins-jobs/templates/_helpers.tpl
- charts/jenkins-jobs/tests/folders_test.yaml
- charts/jenkins-jobs/tests/multibranch_job_test.yaml
With Jenkins JobDSL, the `configure {}` block with [XML transformation](https://github.com/jenkinsci/job-dsl-plugin/wiki/The-Configure-Block#transforming-xml) should only be used as a last resort as it indicates an unsupported directive.
This PR removes the XML transformation in favor of the (now-supported) `gitHubForkDiscovery{ }` block directive.
No changes expected on generated JobDSL: verified with both unit tests (see checks) AND the local manual execution in a k3d Jenkins.
> fix(jenkins-jobs) fix deprecated syntax for GH Fork Discovery traits

- charts/jenkins-jobs/Chart.yaml
- charts/jenkins-jobs/templates/_helpers.tpl
- charts/jenkins-jobs/tests/credentials_test.yaml
Tested with a diff in production:
- No change by default
- Allows removing repeated directives:
```diff
diff --git a/config/jenkins-jobs_infra.ci.jenkins.io.yaml b/config/jenkins-jobs_infra.ci.jenkins.io.yaml
index ae5da785..771022d4 100644
--- a/config/jenkins-jobs_infra.ci.jenkins.io.yaml
+++ b/config/jenkins-jobs_infra.ci.jenkins.io.yaml
@@ -28,6 +28,7 @@ jobsDefinition:
appId: "${GITHUB_APP_INFRA_CI_DOCKER_DEPLOY_ID}"
owner: "jenkins-infra"
privateKey: "${GITHUB_APP_INFRA_CI_DOCKER_DEPLOY_PRIVATE_KEY}"
+    childrenGithubCredential: github-app-infra.ci.jenkins.io-docker-jobs
children:
acceptance-test-harness:
name: "Jenkins CI Acceptance Test Harness (ATH) Docker Image"
@@ -41,51 +42,30 @@ jobsDefinition:
owner: "jenkinsci"
privateKey: "${GITHUB_APP_JENKINSCI_PRIVATE_KEY}" …
```
> feat(jenkins-jobs) allow specifying a GitHub Branch Scan Credential for a given Folder

- charts/jenkins-jobs/Chart.yaml
- charts/jenkins-jobs/README.md
- charts/jenkins-jobs/templates/_jobDSL_credentials.tpl
- charts/jenkins-jobs/templates/_jobDSL_jobs_commons.tpl
- charts/jenkins-jobs/templates/_jobDSL_jobs_multibranch.tpl
- charts/jenkins-jobs/tests/credentials_test.yaml
- charts/jenkins-jobs/tests/folders_test.yaml
- charts/jenkins-jobs/tests/manual/jenkins_values.yaml
- charts/jenkins-jobs/tests/multibranch_job_test.yaml
- Use the properer maintainer in Chart.yaml
- Split template into different files per theme to avoid a big helpers file
- Cleanup indentation in template helpers
- Improve e2e manual testing (avoid crumb errors and add Jenkins default auth.)
----
Note: tried a `diff` on production: it only remove whitespaces and empty lines \o/
----
Note: about file naming conventions in Helm: https://helm.sh/docs/chart_template_guide/named_templates/#partials-and-_-files
> files whose name begins with an underscore (_) are assumed to not have a manifest inside. These files are not rendered to Kubernetes object definitions, but are available everywhere within other chart templates for use.
> chore(jenkins-jobs) code and metadata cleanup

- charts/jenkins-jobs/Chart.yaml
- charts/jenkins-jobs/templates/jcasc-jobs-config.yaml
- charts/jenkins-jobs/tests/credentials_test.yaml
- charts/jenkins-jobs/tests/folders_test.yaml
- charts/jenkins-jobs/tests/multibranch_job_test.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4165#issuecomment-2323979337
This PR is a fixup of both #1313 and #1316.
Unit tests are not enough to catch this issue, but end to end (manual) tests allowed me to reproduce the production error.
Might be worth adding e2e tests (at least here in a first step).
About the fix: when it comes to multi-line strings with YAML: https://yaml-multiline.info/ is the way.
Root cause of the errors is described in https://github.com/helm/helm/issues/5446#issuecomment-866994215:
> However removing any instance of a space before a newline fixed it.
by removing some of the whitespaces (pain with Helm :'(), I ended up into having spaces before empty lines which confused JobDSL.
It was visible by exec-ing on the Jenkins pod and showing the YAML …
> fix(jenkins-jobs) avoid error logs by ensuring no spaces before newlines

- charts/mirrorbits/Chart.yaml
- charts/mirrorbits/templates/_helpers.tpl
- charts/mirrorbits/tests/custom_values_test.yaml
- charts/mirrorbits/tests/defaults_test.yaml
- charts/mirrorbits/tests/values/custom.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2345352162
This PR allows setting up the `OutputMode` directive in mirrorbits. It keeps the default to `auto` (non breaking change)
> feat(mirrorbits) allow setting up OutputMode in mirrorbits configuration

- charts/mirrorbits/Chart.yaml
- charts/mirrorbits/templates/_helpers.tpl
- charts/mirrorbits/templates/deployment.yaml
- charts/mirrorbits/templates/persistentVolumeClaims.yaml
- charts/mirrorbits/templates/persistentVolumes.yaml
- charts/mirrorbits/tests/custom_values_test.yaml
- charts/mirrorbits/tests/defaults_test.yaml
- charts/mirrorbits/tests/values/custom_existingPVC.yaml
- charts/mirrorbits/values.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/2649, this PR allows setting up a mirrorbits instance with existing PVC (either created by another chart release, or statically provisioned).
Tested manually on `publick8s` by setting up a manual HTTP-only instance with success (and reusing the current PVCs of updates.jenkins.io)
> feat(mirrorbits) allow specifying existing PVCs for repository data and geoipdata

- charts/acme/Chart.yaml
- charts/acme/templates/clusterIssuer.yaml
- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/templates/statefulset.yaml
- charts/reports/Chart.yaml
- charts/reports/templates/deployment.yaml
{{- end }} require space around the `end` word
> chore(acp/report/acme): correct a type on {{- end }} missing a space

- updatecli/updatecli.d/httpd-kubectl.yaml
following https://github.com/jenkins-infra/helm-charts/pull/1331 that use kubectl we need to make sure we use a version not too far from the kubernetes version we use on publick8s.
----
tested locally:
```
⚠ Bump Kubectl version for httpd rollout restart:
Source:
✔ [getKubernetesPublick8sVersion] Retrieve the current version of the kubernetes used in production on publick8s
Condition:
✔ [checkDockerImagePublished] Test bitnami/kubectl:<getKubernetesPublick8sVersion> docker image tag
Target:
⚠ [setKubectlToolVersion] Bump Kubectl version for httpd rollout restart
Run Summary
===========
Pipeline(s) run:
* Changed:    1
* Failed:     0
* Skipped:    0
* Succeeded:  0
* Total:      1
```
> chore(updatecli): add a manifest to bump kubectl version to the kubernetes used on publick8s

- updatecli/updatecli.d/httpd-kubectl.yaml
following #1350 need to bump the helm chart version also
> chore(updatecli): hotfix use `kind: helmchart` to handle the helm chart bump with the tag update

- charts/httpd/Chart.yaml
- charts/httpd/templates/deployment.yaml
- charts/httpd/tests/custom_values_test.yaml
- charts/httpd/tests/defaults_test.yaml
- charts/httpd/tests/values/custom.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2364054995
This PR allows the chart to mount the `htdocs` directory from a sub directory in the persistent volume.
- Unit tests added
- Tested with success with an emptyDir on a local k3d ephemeral cluster
- Tested with success by installing a new HTTPD chart using a subdir on production (with the Azure File storage created in https://github.com/jenkins-infra/azure/pull/840
> feat(httpd) allow using subdir for the htdocs volume mount

- charts/httpd/Chart.yaml
- charts/httpd/templates/_helpers.tpl
- charts/httpd/templates/httpdRestart.yaml
- charts/httpd/tests/custom_values_test.yaml
- charts/httpd/tests/values/custom.yaml
Closes https://github.com/jenkins-infra/helm-charts/issues/1356
Tested with success in a local k3d cluster
>  fix(httpd) restrict cronjob resources name to 52 chars. max. 

- charts/httpd/Chart.yaml
- charts/httpd/templates/configmap.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4312#issuecomment-2380584671
This PR ensure send file is disabled as the `htdocs` is mounted on the network.
HTTPD configuration tells us it's disabled by default but better safe than sorry + explicit disabling is safer for maintenance.
> feat(httpd) disable `EnableSendfile` as document root is on the network

- charts/jenkins-jobs/Chart.yaml
- charts/jenkins-jobs/templates/_jobDSL_jobs_multibranch.tpl
- charts/jenkins-jobs/tests/multibranch_job_test.yaml
- charts/jenkins-jobs/values.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4355#issuecomment-2488678996
This PR introduces 2 changes on the chart:
- A bugfix (we expect progress updates to be disabled when GH status checks are disabled
- A new feature: allow disabling the GitHub Notifications at all
> feat(jenkins-jobs) allow disabling the GitHub Notifications

- charts/rsyncd/Chart.yaml
- charts/rsyncd/templates/service.yaml
Minor change to avoid warning when creating an Azure PLS
> fix(rsyncd) service: do not specify an empty 'loadBalancerSourceRanges' when using a LB with no whiteliste specified

- charts/rsyncd/Chart.yaml
- charts/rsyncd/templates/deployment.yaml
This PR fixes the health probes for `rsyncd` which is failing its initial deployment due to host key generation taking more time than expected
> fix(rsyncd) increase helath probes failures threshold for SSHD

- charts/mirrorbits/Chart.yaml
- charts/mirrorbits/templates/deployment.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4402
This PR introduces the `subPath` mount option so we can centralize to only a single NFS PVC if needed
> feat(mirrorbits) allow to mount a PVC with a subdir option

- charts/rsyncd/Chart.yaml
- charts/rsyncd/templates/deployment.yaml
- charts/rsyncd/tests/custom_values_sshd_test.yaml
- charts/rsyncd/tests/values/custom_sshd.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4402#issuecomment-2505362943
> Each time the `rsyncd` (with sshd enabled) restarts on a new node, it regenerates the SSHD host keys which fails any new connections.
This PR updates the chart (and entrypoint - ref. https://github.com/jenkins-infra/docker-rsyncd/pull/29) to allow specifying a directory in which to get existing SSH host keys at restart through the `configuration.sshd.persistentHostKeys` value.
Tested locally on k3s by using a component's specified PVC with a subdir:
- Installed the chart one time without the persistence key enabled
- Copied the generated keys in the PVC's subdir
- Ran one time a rsync command: it asked the usual "yes/no" question about host fingerprint. Accepted tyo have my known_host up to date.
- …
> feat(rsyncd) allow specifying path to existing host keys through `configuration.sshd.persistentHostKeys`

- charts/rsyncd/Chart.yaml
- charts/rsyncd/templates/_helpers.tpl
- charts/rsyncd/templates/configmap.rsyncd-conf.yaml
- charts/rsyncd/templates/deployment.yaml
- charts/rsyncd/templates/secrets.yaml
- charts/rsyncd/templates/service.yaml
- charts/rsyncd/tests/custom_values_rsyncd_test.yaml
- charts/rsyncd/tests/custom_values_sshd_test.yaml
- charts/rsyncd/tests/defaults_test.yaml
- charts/rsyncd/tests/values/custom_rsyncd.yaml
- charts/rsyncd/tests/values/custom_sshd.yaml
- charts/rsyncd/values.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4402
New feature: specify hostkeys through `configuration.sshd.hostKeys` as individual "files" (mounted as secret)
BREAKING CHANGE: remove `configuration.sshd.persistentHostKeys`
BREAKING CHANGE: Replace `configuration.sshd.rsyncd_daemon` by `configuration.sshd.rsyncdDaemon`
BREAKING CHANGE: Replace `configuration.sshd.public_key` by `configuration.sshd.publicKey`
BREAKING CHANGE: Replace `service.whitelisted_sources` by `service.whitelistedSources`
> feat!(rsyncd) deprecate `configuration.sshd.hostKeys` and all "snake cased" values and replace them by "camel cased" values

- charts/rsyncd/Chart.yaml
- charts/rsyncd/templates/deployment.yaml
- charts/rsyncd/tests/custom_values_rsyncd_test.yaml
- charts/rsyncd/tests/custom_values_sshd_test.yaml
- charts/rsyncd/tests/values/custom_rsyncd.yaml
- charts/rsyncd/tests/values/custom_sshd.yaml
> feat(rsyncd) allow specifying a sub directory for each component to mount (instead of the root)

- charts/geoipupdates/Chart.yaml
- charts/geoipupdates/templates/cronjob.yaml
- charts/geoipupdates/tests/custom_values_test.yaml
- charts/geoipupdates/tests/defaults_test.yaml
- charts/geoipupdates/tests/values/custom_geoipupdater.yaml
- charts/geoipupdates/values.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4436
removing `update_frequency` useless in cronjob
> feat(geoipupdate): remove `update_frequency` parameter not used in cronjob

- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/templates/nginx-proxy-configmap.yaml
- charts/artifact-caching-proxy/tests/proxy_cache_config_test.yaml
- charts/artifact-caching-proxy/values.yaml
This PR sets the [proxy_ssl_server_name](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_ssl_server_name) to on by default.
Without this, we get an `SSL alert number 40` when trying to proxy the jenkins-updates.cloudbees.com site.
```sh
2025/01/09 09:28:40 [error] 20#20: *43 SSL_do_handshake() failed (SSL: error:0A000410:SSL routines::ssl/tls alert handshake failure:SSL alert number 40) while SSL handshaking to upstream, client: 127.0.0.1, server: _, request: "GET /download/plugins/beer/1.0/beer.hpi HTTP/1.1", upstream: "https://18.160.78.88:443/download/plugins/beer/1.0/beer.hpi", host: "127.0.0.1:8080"
2025/01/09 09:28:40 [warn] 20#20: *43 upstream server temporarily disabled while SSL handshaking to upstream, client: 127.0.0.1, server: _, request: "GET …
```
> Add directive 'proxy_ssl_server_name on' by default

- charts/jenkins-kubernetes-agents/Chart.yaml
- charts/jenkins-kubernetes-agents/templates/rbac.yaml
- charts/jenkins-kubernetes-agents/tests/custom_values_test.yaml
- charts/jenkins-kubernetes-agents/values.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4319#issuecomment-2573143011
following https://github.com/jenkins-infra/terraform-aws-sponsorship/pull/76 and https://github.com/jenkins-infra/terraform-aws-sponsorship/pull/77
prepare the helm chart to handle the kubernetes groups and allow credential less connexion
> feat(jenkins-kubernetes-agents) allow specifying groups bound to the RBAC role used by Jenkins

- charts/docker-registry/.helmignore
- charts/docker-registry/Chart.yaml
- charts/docker-registry/templates/_helpers.tpl
- charts/docker-registry/templates/configmap.yaml
- charts/docker-registry/templates/secret.yaml
- charts/docker-registry/templates/service.yaml
- charts/docker-registry/templates/statefulset.yaml
- charts/docker-registry/values.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4321
This chart has been tested manually (for now). It's aimed at providing as a Docker Registry (official name is [CNCF Distribution](https://distribution.github.io/distribution/)) acting as proxy mirror of the DockerHub.
It's inspired by https://github.com/twuni/docker-registry.helm.
It lacks unit tests and a few features from https://github.com/twuni/docker-registry.helm.
> feat: introduce docker-registry chart

- charts/javadoc/Chart.yaml
- charts/javadoc/templates/nginx-configmap.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4594
We do not want Jenkins contributors to receive an HTTP/404 errors when trying to get the javadoc for this component.
Let's add a permanent redirect for keeping the user experience.
> feat(javadoc) redirect KK github-api javadoc to its new home

- charts/javadoc/Chart.yaml
- charts/javadoc/templates/_helpers.tpl
This PR fixes the deployment error below introduced by https://github.com/jenkins-infra/helm-charts/pull/1592
```
Error: UPGRADE FAILED: release javadoc failed, and has been rolled back due to atomic being set: cannot patch "javadoc" with kind PodDisruptionBudget: PodDisruptionBudget.policy "javadoc" is invalid: metadata.labels: Invalid value: "Jenkins Infra Team": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?') && cannot patch "javadoc" with kind ConfigMap: ConfigMap "javadoc" is invalid: metadata.labels: Invalid value: "Jenkins Infra Team": a valid label must be an …
```
> fix(javadoc) remove maintainer from labels as it may contains forbidden chars

- charts/maven-cacher/Chart.yaml
- charts/maven-cacher/templates/_helpers.tpl
- charts/maven-cacher/templates/configmap-maven-settings.yaml
- charts/maven-cacher/templates/configmap-scripts.yaml
- charts/maven-cacher/templates/cronjob.yaml
- charts/maven-cacher/tests/custom_values_test.yaml
- charts/maven-cacher/tests/defaults_test.yaml
- charts/maven-cacher/tests/values/custom.yaml
- charts/maven-cacher/values.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4525
This new chart embeds a script inspired by https://github.com/jenkinsci/bom/pull/4667
Tested multiple time manually.
> feat: init the maven-cacher chart

- charts/maven-cacher/Chart.yaml
- charts/maven-cacher/values.yaml
If we want to pin to a tag, it is in the release (and we will do it there)
> fix(maven-cacher) defaults to latest tag

- charts/ldap/Chart.yaml
- charts/ldap/templates/service.yaml
- charts/ldap/tests/custom_values_test.yaml
- charts/ldap/tests/defaults_values_test.yaml
- charts/ldap/tests/values/custom.yaml
- charts/ldap/values.yaml
instead of using a list of string, for easier maintenance (updatecli may track keys easier than moving array targets)
BREAKING CHANGE: Deprecates `service.whitelisted_sources` in favor of `service.lbAllowSources`
Tested manually with https://github.com/jenkins-infra/kubernetes-management/pull/6379. The order changes (as the ` range` helm gotpl function iterates on map with lexicographical order):
```diff
ldap, ldap, Service (v1) has changed:
apiVersion: v1
kind: Service
metadata:
name: ldap
labels:
app.kubernetes.io/name: ldap
-     helm.sh/chart: ldap-2.0.5
+     helm.sh/chart: ldap-3.0.0
app.kubernetes.io/instance: ldap
app.kubernetes.io/managed-by: Helm
annotations:
service.beta.kubernetes.io/azure-pip-name: ldap-jenkins-io-ipv4 …
```
> feat(ldap)!: specify LoadBalancer source list with a map `service.lbAllowSources`

- charts/ldap/Chart.yaml
- charts/ldap/templates/service.yaml
- charts/ldap/tests/custom_values_test.yaml
- charts/ldap/tests/values/custom.yaml
Following up #1616 , we'll need to provide a list of CIDR for some items.
This change allows specifying the list of CIDR with a in the form of a comma-separated string
> feat(ldap) allow specifying a comma-separated list of CIDR for `spec.lbAllowSources`

- updatecli/updatecli.d/plugin-health-scoring.yaml
As it is possible to ask UpdateCLI to request review, let's make sure the plugin health scoring maintainers are requested. 
We could have a team in `github/jenkins-infra` about those users but for now direct username should work.
> chore(updatecli): Automatically request reviews from plugin health scoring maintainers

- charts/plugin-health-scoring/Chart.yaml
- charts/plugin-health-scoring/templates/deployment.yaml
- charts/plugin-health-scoring/tests/custom_values_test.yaml
- charts/plugin-health-scoring/tests/defaults_test.yaml
- charts/plugin-health-scoring/tests/values/custom.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4678#issuecomment-2931064411
We need to ensure PHS logs are collected with the proper tags to allow Datadog autodiscovery to work: as such we need to support custom annotations on this deployment (ref. https://docs.datadoghq.com/containers/kubernetes/log/)
> feat(plugin-health-score) allow specifying custom annotations instead of unused config checksum

- charts/nginx-website/Chart.yaml
- charts/nginx-website/templates/deployment.yaml
- charts/nginx-website/tests/custom_values_locations_test.yaml
- charts/nginx-website/tests/custom_values_test.yaml
- charts/nginx-website/tests/defaults_test.yaml
- charts/nginx-website/tests/values/custom-locations.yaml
- charts/nginx-website/tests/values/custom.yaml
- charts/nginx-website/values.yaml
Another chart for which we want to pass custom annotations on the deployment.
Note: also removes the "I have no idea what is the purpose of it" config checksum annotation
> feat(nginx-website) allow specifying custom pod annotations

- charts/maven-cacher/Chart.yaml
- charts/maven-cacher/templates/configmap-scripts.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4752
> fix(maven-cacher) write the cache archive directly to the destination instead of using /tmp to avoid weird disk space issues

- charts/artifact-caching-proxy/Chart.yaml
- charts/artifact-caching-proxy/templates/nginx-proxy-configmap.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4747#issuecomment-3150474047
The artifacts retrieved after performing a redirection in the upstream/backend part (e.g. Nginx had to re-emit a new HTTP request to the `Location` header from the initial proxied upstream response) should be cached.
I'm not sure if it even worked as the `proxy-cache.conf` must be included to enable caching of the retrieved file, despite the `proxy_cache_key` directive set.
Tested on local ACP installation and manually in production
> fix(artifact-caching-proxy) ensure file caching is enabled when handling proxy redirected URLs
